const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const Zip=require('../app/vendor/jszip-3.10.1.min.js'),pack=require('../app/accounting-package.js');
test('one button refreshes KSeF and mail, downloads one ZIP and blocks failures and cancellation',async()=>{
 const elements=new Map();const node=()=>({value:'',dataset:{},hidden:false,disabled:false,replaceChildren(){},click(){downloads.push(this.download);},remove(){}});
 for(const id of ['cfAccountingMonth','cfAccountingInputs','cfAccountingAllStart','cfAccountingAllCancel','cfAccountingAllStatus','cfKsefNip','cfKsefToken','cfKsefEnvironment','cfKsefStart','cfKsefSave','cfKsefCancel','cfKsefStatus','cfKsefpurchases','cfKsefsales'])elements.set(id,node());
 elements.get('cfAccountingMonth').value='2026-08';elements.get('cfKsefNip').value='5260250995';elements.get('cfKsefEnvironment').value='production';
 const downloads=[],actions=[];let failMail=false,abortMail=false,controller;
 const context={AbortController,DOMException,Blob,setTimeout:()=>{},URL:{createObjectURL:()=> 'blob:zip',revokeObjectURL(){}},CF_SUPABASE_URL:'https://example.com',CF_SUPABASE_KEY:'public',document:{readyState:'loading',addEventListener(){},getElementById:id=>elements.get(id),createElement:node,body:{appendChild(){}}},window:{cfBackupBridge:{isAdmin:()=>true,getClient:()=>({auth:{getSession:async()=>({data:{session:{access_token:'jwt'}}})}})},JSZip:Zip,CFAccountingPackage:{build:data=>pack.build(data,Zip)},CFAccountingMail:{exportFiles:async signal=>{actions.push('mail');assert.equal(elements.get('cfAccountingInputs').disabled,true);if(failMail)throw new Error('mail unavailable');if(abortMail){context.harness.cancel();throw new DOMException('cancelled','AbortError');}return [{name:'statement.pdf',blob:new Blob(['bank mail'])}];}}},fetch:async(url,options)=>{const body=JSON.parse(options.body);actions.push(body.action);return {ok:true,json:async()=>body.action==='start'?{month:'2026-08',jobs:[{kind:'purchases',ticket:'p'},{kind:'sales',ticket:'s'}]}:{status:'ready',invoiceCount:0,size:0}};}};
 vm.createContext(context);vm.runInContext(fs.readFileSync('app/accounting-documents-v1510.js','utf8').replace(/\}\)\(\);\s*$/,'globalThis.harness={downloadAll,cancel:()=>allRun.abort(),setPdf:files=>selectedFiles.organizer=files};})();'),context);
 context.harness.setPdf([{name:'organizer.pdf',arrayBuffer:async()=>new Uint8Array([1,2,3]).buffer}]);
 async function run(){elements.get('cfKsefToken').value='token';await context.harness.downloadAll();assert.equal(elements.get('cfAccountingInputs').disabled,false);assert.equal(elements.get('cfAccountingAllCancel').hidden,true);}
 await run();assert.deepEqual(downloads,['Dokumenty-2026-08.zip']);assert.deepEqual(actions,['start','status','status','mail']);assert.match(elements.get('cfAccountingAllStatus').textContent,/mOrganizer: 1 PDF/);
 failMail=true;await run();assert.equal(downloads.length,1);assert.match(elements.get('cfAccountingAllStatus').textContent,/Nie utworzono.*mail unavailable/);
 failMail=false;abortMail=true;await run();assert.equal(downloads.length,1);assert.match(elements.get('cfAccountingAllStatus').textContent,/Anulowano/);
 elements.get('cfKsefToken').value='';await context.harness.downloadAll();assert.equal(downloads.length,1);assert.match(elements.get('cfAccountingAllStatus').textContent,/Nie utworzono.*KSeF/);
});
