const test=require('node:test'),assert=require('node:assert/strict');const h=require('../app/accounting-history.js'),{reconcile}=require('../app/accounting-reconcile.js');
const invoice=(extra={})=>({date:'2026-08-31',nip:'1234567890',nrKSeF:'1234567890-20260831-123456789abc-ab',number:'FV/08/2026',seller:'Szoltysek Transport',gross:'500.00',currency:'PLN',type:'VAT',accounts:[],...extra});
const context={month:'2026-08',nip:'6351861297',environment:'production'};
function client(error=null){const rows=new Map(),filters={};const c={auth:{getUser:async()=>({data:{user:{id:'owner'}}})},from:()=>({upsert:(row,options)=>{c.last={row,options};if(!error)rows.set(JSON.stringify([row.user_id,row.environment,row.nip,row.month]),row);return Promise.resolve({error});},select:()=>{const q={eq:(key,value)=>{filters[key]=value;return q;},in:(key,values)=>{filters[key]=values;return q;},then:(resolve,reject)=>Promise.resolve({error,data:[...rows.values()].filter(row=>Object.entries(filters).every(([k,v])=>Array.isArray(v)?v.includes(row[k]):row[k]===v))}).then(resolve,reject)};return q;}})};return c;}
test('monthly metadata survives a new load, replaces duplicate snapshots and scopes owner, NIP and environment',async()=>{
 const c=client();await h.save(c,context,[invoice(),invoice()]);assert.equal(c.last.row.invoice_count,1);assert.equal(c.last.options.onConflict,'user_id,environment,nip,month');assert.equal(c.last.row.user_id,'owner');await h.save(c,context,[invoice()]);const result=await h.load(c,{...context,month:'2026-09'});assert.equal(result.snapshots.length,1);assert.equal(result.snapshots[0].invoices[0].seller,'Szoltysek Transport');assert.deepEqual(result.expected,['2026-09','2026-08','2026-07','2026-06']);assert.equal((await h.load(c,{...context,nip:'1111111111'})).snapshots.length,0);assert.equal((await h.load(c,{...context,environment:'test'})).snapshots.length,0);
});
test('empty completed months are remembered and errors are surfaced',async()=>{const c=client();await h.save(c,context,[]);assert.equal((await h.load(c,context)).snapshots[0].invoice_count,0);await assert.rejects(h.save(client({message:'denied'}),context,[invoice()]),/zapisać.*denied/);await assert.rejects(h.load(client({message:'denied'}),context),/odczytać.*denied/);assert.throws(()=>h.cleanInvoices([invoice({date:'2026-07-31'})],'2026-08'),/niepełne/);assert.deepEqual(h.months('2026-01'),['2026-01','2025-12','2025-11','2025-10']);});
const bank={month:'2026-09',statement:{account:'12345678901234567890123456',currency:'PLN',operations:[{booked:'2026-09-10',amount:-50000n,party:'Szoltysek Transport',title:'Zapłata',description:'PRZELEW'}]}};
function compare(current=[invoice({date:'2026-09-30',number:'FV/09/2026',nrKSeF:'next-invoice',gross:'600.00'})],old=[invoice()]){return reconcile({month:'2026-09',bankResults:[bank],purchases:{month:'2026-09',count:current.length,invoices:current},history:{expected:h.months('2026-09'),snapshots:[{month:'2026-08',invoices:old}]}});}
test('September payment matches exact August invoice instead of September amount, historical invoices stay out of current unpaid list',()=>{const r=compare();assert.equal(r.counts.matched,1);assert.match(r.rows[0].reason,/2026-08.*2026-09/);assert.equal(r.rows[0].candidates.find(c=>c.invoiceIndex===r.rows[0].matchedInvoice).invoice.number,'FV/08/2026');assert.equal(r.unmatchedInvoices.length,1);assert.equal(r.unmatchedInvoices[0].sourceMonth,'2026-09');assert.ok(r.warnings.some(w=>w.includes('2026-07')));});
test('same supplier and identical amounts across months stay ambiguous; metadata alone supports control without new current export',()=>{assert.equal(compare([invoice({date:'2026-09-01',number:'FV/09/2026',nrKSeF:'other-invoice'})]).counts.uncertain,1);const r=reconcile({month:'2026-09',bankResults:[bank],history:{expected:h.months('2026-09'),snapshots:[{month:'2026-08',invoices:[invoice()]}]}});assert.equal(r.counts.matched,1);assert.equal(r.unmatchedInvoices.length,0);});
