const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const Zip=require('../app/vendor/jszip-3.10.1.min.js'),pack=require('../app/accounting-package.js');
test('bottom button packs prepared sources without restarting exports or conversion, allows optional sources, and blocks partial downloads',async()=>{
 const elements=new Map();const node=()=>({value:'',dataset:{},hidden:false,disabled:false,replaceChildren(){},click(){downloads.push(this.download);},remove(){}});
 for(const id of ['cfAccountingMonth','cfAccountingInputs','cfAccountingAllStart','cfAccountingAllCancel','cfAccountingAllStatus','cfAccountingAllConfirm','cfAccountingReview'])elements.set(id,node());elements.get('cfAccountingMonth').value='2026-08';
 const downloads=[],archives=[];let failMail=false,abortMail=false,mailFiles=[{name:'selected.pdf',blob:new Blob(['bank mail'])}];
 const context={AbortController,DOMException,Blob,setTimeout:()=>{},URL:{createObjectURL:blob=>{archives.push(blob);return 'blob:zip';},revokeObjectURL(){}},document:{readyState:'loading',addEventListener(){},getElementById:id=>elements.get(id),createElement:node,body:{appendChild(){}}},window:{cfBackupBridge:{isAdmin:()=>true},JSZip:Zip,CFAccountingReconcile:{reconcile:()=>({counts:{}}),render:()=>{},attachmentFiles:()=>[]},CFAccountingPackage:{build:data=>pack.build(data,Zip)},CFAccountingMail:{exportFiles:async signal=>{assert.equal(elements.get('cfAccountingInputs').disabled,true);if(failMail)throw new Error('mail unavailable');if(abortMail){context.harness.cancel();throw new DOMException('cancelled','AbortError');}return mailFiles;}}},fetch:()=>{throw new Error('No automatic KSeF or configuration requests allowed');}};
 vm.createContext(context);const source=fs.readFileSync('app/accounting-documents-v1510.js','utf8');vm.runInContext(source.replace(/\}\)\(\);\s*$/,'globalThis.harness={downloadAll,cancel:()=>allRun.abort(),setSources:({ksef={},bank=[],pdf=[],csv=[]})=>{ksefResults=ksef;bankResults=bank;selectedFiles.organizer=pdf;bankFiles=csv;invalidateReview();}};})();'),context);
 const z=new Zip();z.file('invoice.pdf','original invoice');const invoice={month:'2026-08',count:1,format:'pdf',blob:new Blob([await z.generateAsync({type:'uint8array'})])};
 const prepared={ksef:{purchases:invoice,sales:{month:'2026-08',count:0}},bank:[{month:'2026-08',filename:'prepared.txt',bytes:new TextEncoder().encode('prepared MT940')}],pdf:[{name:'organizer.pdf',arrayBuffer:async()=>new Uint8Array([1,2,3]).buffer}],csv:[{}]};
 async function run(){const before=downloads.length;await context.harness.downloadAll();assert.equal(downloads.length,before);if(!elements.get('cfAccountingAllConfirm').hidden)await context.harness.downloadAll(true);assert.equal(elements.get('cfAccountingInputs').disabled,false);assert.equal(elements.get('cfAccountingAllCancel').hidden,true);}
 context.harness.setSources(prepared);elements.get('cfAccountingAllConfirm').hidden=true;await context.harness.downloadAll(true);assert.equal(downloads.length,0);assert.match(elements.get('cfAccountingAllStatus').textContent,/Ponownie uruchom/);await run();await run();assert.deepEqual(downloads,['Dokumenty-2026-08.zip','Dokumenty-2026-08.zip']);
 const zip=await Zip.loadAsync(await archives[0].arrayBuffer());assert.equal(await zip.file('8 SIERPIEŃ/faktury zakupowe/KSEF/invoice.pdf').async('string'),'original invoice');assert.equal(await zip.file('8 SIERPIEŃ/wyciągi bankowe/prepared.txt').async('string'),'prepared MT940');assert.ok(zip.file('8 SIERPIEŃ/wyciągi bankowe/selected.pdf'));
 failMail=true;await run();assert.equal(downloads.length,2);assert.match(elements.get('cfAccountingAllStatus','cfAccountingAllConfirm','cfAccountingReview').textContent,/Nie utworzono.*mail unavailable/);
 failMail=false;abortMail=true;await run();assert.equal(downloads.length,2);assert.match(elements.get('cfAccountingAllStatus','cfAccountingAllConfirm','cfAccountingReview').textContent,/Anulowano/);
 abortMail=false;mailFiles=[];context.harness.setSources({pdf:prepared.pdf});await run();assert.equal(downloads.length,3);assert.match(elements.get('cfAccountingAllStatus','cfAccountingAllConfirm','cfAccountingReview').textContent,/KSeF: 0 zakupowych/);
 context.harness.setSources({csv:[{}]});await run();assert.equal(downloads.length,3);assert.match(elements.get('cfAccountingAllStatus','cfAccountingAllConfirm','cfAccountingReview').textContent,/najpierw przekonwertuj/);
 context.harness.setSources({});await run();assert.equal(downloads.length,3);assert.match(elements.get('cfAccountingAllStatus','cfAccountingAllConfirm','cfAccountingReview').textContent,/Przygotuj dokumenty/);
 assert.ok(source.indexOf('id="cfAccountingAllStart"')>source.indexOf("'</fieldset>'"));
});
