const {chromium}=require('playwright'),fs=require('fs'),assert=require('node:assert/strict');
const root=require('node:path').resolve(__dirname,'..');
(async()=>{
 const executablePath=process.env.CF_CHROMIUM_EXECUTABLE,args=process.env.CF_CHROMIUM_ARGS?JSON.parse(process.env.CF_CHROMIUM_ARGS):[];const vault=await import(root+'/app/priv/vault.js'),salt=vault.newSalt(),key=await vault.keyFor('test-pin-123',salt);
 const entry={id:'cash-existing',amount:12345,type:'income',description:'Zachowana gotówka',createdAt:'2026-10-07T17:00:00Z'};const state={version:1,rules:[],transactions:[],imports:[],cash:[entry]};let saved={envelope:await vault.seal(state,key,salt),revision:1},holdMode=false,release;
 let earningsRows=[{id:'e1',work_date:'2026-10-07',contractor:'Testowy kontrahent',description:'Zachowany zarobek',total_amount:1000,my_amount:800,employee_amount:200,employee_name:'Pracownik',employee_paid:false}],calls=0;
 const browser=await chromium.launch({headless:true,...(executablePath?{executablePath,args}:{})});const page=await browser.newPage();const errors=[];await page.clock.install({time:new Date('2026-10-07T19:00:00Z')});page.on('pageerror',e=>errors.push(e.message));
 await page.exposeFunction('mockLoad',()=>saved);await page.exposeFunction('mockSave',({p_envelope,p_revision})=>{assert.equal(p_revision,saved.revision);saved={envelope:p_envelope,revision:saved.revision+1};return {data:saved.revision};});
 await page.exposeFunction('mockEarnings',()=>{calls++;return holdMode?new Promise(r=>release=r):{data:earningsRows};});
 await page.exposeFunction('mockUpdateEarning',({id,payload})=>{Object.assign(earningsRows.find(r=>r.id===id),payload);return {};});
 await page.addInitScript(()=>{
  window.testAdmin=true;let listener;
  const client={auth:{getUser:async()=>({data:{user:{id:'test-admin'}}}),onAuthStateChange:fn=>{listener=fn;return {data:{subscription:{unsubscribe:()=>{listener=null;}}}};}},rpc:async(name,args)=>name==='cf_is_admin'?{data:true}:window.mockSave(args),from:name=>{
   if(name==='cf_payment_vaults')return {select:()=>({eq:()=>({maybeSingle:async()=>({data:await window.mockLoad()})})})};
   if(name==='cf_earnings')return {select:()=>({order:()=>window.mockEarnings()}),update:payload=>({eq:(_,id)=>window.mockUpdateEarning({id,payload})})};
   return {select:()=>({order:async()=>({data:[]}),in:async()=>({data:[]})})};
  }};window.mockClient=client;window.testSignOut=()=>listener?.('SIGNED_OUT');window.supabase={createClient:()=>client};window.cfBackupBridge={isAdmin:()=>window.testAdmin,getClient:()=>client};
 });
 await page.route('https://cdn.jsdelivr.net/**',r=>r.fulfill({contentType:'text/javascript',body:''}));
 await page.route('https://raw.githubusercontent.com/**',r=>r.fulfill({json:{ok:true,prices:{petrol95:7.07,diesel:8.18},currency:'PLN',as_of:'2026-10-07'}}));
 await page.route('https://photon.komoot.io/**',r=>r.fulfill({json:{features:[{properties:{name:new URL(r.request().url()).searchParams.get('q'),city:'Test',country:'Polska'},geometry:{coordinates:[18.9,50.17]}}]}}));
 await page.route('https://routing.openstreetmap.de/**',r=>r.fulfill({json:{code:'Ok',routes:[{distance:150000,legs:[{distance:150000}]}]}}));
 const index=fs.readFileSync(root+'/app/index.html','utf8'),styles=[...index.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/g)].map(m=>m[1]).join('\n');
 const earnings=index.slice(index.indexOf('let cfEarningsUnlocked=false;'),index.indexOf('\nfunction cfOpenCompanyForm'));
 await page.route('http://localhost:4189/app/**',r=>{const name=new URL(r.request().url()).pathname;if(name==='/app/test-finances')return r.fulfill({contentType:'text/html',body:'<html><head><style>'+styles+'</style></head><body><div id="original"><input id="draft" value="zachowany tekst"><button id="tile">Moje finanse</button></div><div id="modalRoot"></div></body></html>'});const path=root+name;if(!fs.existsSync(path))return r.abort();return r.fulfill({contentType:name.endsWith('html')?'text/html':'text/javascript',body:fs.readFileSync(path)});});
 await page.goto('http://localhost:4189/app/test-finances');await page.addScriptTag({content:`const cfSupabase=window.mockClient;function cfIsAdmin(){return window.testAdmin;}function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}function showToast(s){window.lastToast=s;}async function cfRefreshExchangeRate(){}window.CFExchange={earnings:r=>r};window.CFPeriods={attach:()=>{}};`+earnings});await page.addScriptTag({content:fs.readFileSync(root+'/app/dojazdy.js','utf8')});await page.addScriptTag({content:fs.readFileSync(root+'/app/finances.js','utf8')});
 await page.evaluate(()=>window.CFFinance.open());const frame=page.frameLocator('#cfFinancePrivate iframe');await frame.locator('#unlockForm').waitFor({state:'visible'});assert.equal(calls,0);assert(await page.locator('.cf-finance-tabs').isHidden());
 await page.evaluate(()=>window.dispatchEvent(new MessageEvent('message',{origin:location.origin,source:window,data:{type:'cf-finances-unlocked'}})));assert.equal(await page.evaluate(()=>CFFinance.isUnlocked()),false);
 await frame.locator('#pin').fill('wrong-pin');await frame.locator('#unlock').click();await frame.getByText('Nieprawidłowy PIN lub hasło.',{exact:true}).waitFor();assert.equal(calls,0);
 const unlock=async()=>{await frame.locator('#pin').fill('test-pin-123');await frame.locator('#unlock').click();await page.locator('.cf-finance-tabs').waitFor({state:'visible'});};await unlock();await page.getByText('Zachowany zarobek',{exact:false}).waitFor();assert.equal(await page.locator('[role=tab]').count(),4);
 await page.click('[data-tab=payments]');assert.equal(await frame.locator('#cash').count(),0);await frame.locator('#editList').waitFor({state:'visible'});
 await page.click('[data-tab=cash]');await frame.getByText('Zachowana gotówka',{exact:true}).waitFor();assert.match(await frame.locator('#cashBalance').textContent(),/123,45/);await frame.locator('#cashAmount').fill('12,5');await frame.locator('#cashDescription').fill('Wydatek po przeniesieniu');await frame.locator('#cashType').selectOption('expense');await frame.locator('#cashSave').click();await frame.getByText('Wydatek po przeniesieniu',{exact:true}).waitFor();assert.match(await frame.locator('#cashBalance').textContent(),/110,95/);
 await page.click('[data-tab=trips]');await page.fill('#cfDrivePoint0','Katowice');await page.fill('#cfDrivePoint1','Kraków');await page.click('[data-tab=earnings]');await page.click('[data-tab=trips]');assert.equal(await page.inputValue('#cfDrivePoint0'),'Katowice');assert.equal(calls,1);
 await page.locator('.cf-drive-point').nth(0).getByRole('button',{name:'Szukaj',exact:true}).click();await page.locator('.cf-drive-options button').first().click();await page.locator('.cf-drive-point').nth(1).getByRole('button',{name:'Szukaj',exact:true}).click();await page.locator('.cf-drive-options button').first().click();await page.click('#cfDriveUsePrice');await page.getByRole('button',{name:'Oblicz dojazd',exact:true}).click();await page.getByText('110,43 zł',{exact:true}).waitFor();
 await page.screenshot({path:'/tmp/finances-trips.png'});

 await page.click('[data-tab=earnings]');await page.screenshot({path:'/tmp/finances-earnings.png'});await page.locator('[data-paid=e1]').check();await page.waitForFunction(()=>document.querySelector('[data-paid=e1]').checked);assert.equal(earningsRows[0].employee_paid,true);
 await page.click('[data-tab=cash]');for(const width of [390,1024,1440]){await page.setViewportSize({width,height:900});const shell=await page.locator('.cf-finance-shell').boundingBox();assert(shell.x>=0&&shell.x+shell.width<=width);await page.screenshot({path:'/tmp/finances-'+width+'.png'});}
 await page.click('[data-lock]');assert.equal(await page.evaluate(()=>CFFinance.isUnlocked()),false);assert.equal(await page.locator('#cfEarningsList').count(),0);assert.equal(await page.locator('#cfDrivePoint0').count(),0);assert.equal(await frame.locator('#cashRows').count(),0);assert(await page.locator('.cf-finance-tabs').isHidden());
 await unlock();await page.click('[data-tab=cash]');await frame.getByText('Wydatek po przeniesieniu',{exact:true}).waitFor();await frame.getByRole('button',{name:'Usuń wpis: Wydatek po przeniesieniu',exact:true}).click();await frame.getByText('Wydatek po przeniesieniu',{exact:true}).waitFor({state:'hidden'});assert.match(await frame.locator('#cashBalance').textContent(),/123,45/);
 await page.click('[data-lock]');holdMode=true;await unlock();await page.click('[data-lock]');holdMode=false;release({data:earningsRows});await page.waitForTimeout(100);assert.equal(await page.locator('#cfEarningsList').count(),0);
 await page.click('[data-close]');assert.equal(await page.inputValue('#draft'),'zachowany tekst');assert.equal(await page.locator('#cfFinanceWindow').count(),0);assert.equal(await page.locator('#original').evaluate(el=>el.inert),false);
 await page.evaluate(()=>{window.testAdmin=false;CFFinance.open();});assert.equal(await page.locator('#cfFinanceWindow').count(),0);assert.deepEqual(errors,[]);assert.deepEqual((await vault.open(saved.envelope,key)).cash,[entry]);console.log('PASS finances: existing password/data, wrong PIN and forged message blocked, four tabs, earnings loading/edit, cash movement/save/delete, trip draft retained and route calculated, lock clears all panes, late earnings response ignored, admin-only, 3 layouts, previous screen preserved');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
