const {test}=require('node:test'),assert=require('node:assert/strict'),P=require('../app/priv/engine.js'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const rule={id:'netflix',name:'Netflix',recipient:'NETFLIX.COM Amsterdam NL',currency:'PLN',expected:3700,account:'',accounts:[],day:25,start:'2026-01',end:null,offset:0,phrase:''};
const payment={id:'p1',recipient:'Netflix.com Los Gatos NL',currency:'PLN',date:'2026-05-25',amount:3300,account:'',title:''};
test('similar name prompts are currency-specific and do not automatically match',()=>{assert.deepEqual(P.similarRules(payment,[rule]).map(r=>r.id),['netflix']);assert.equal(P.matches(rule,payment),false);assert.equal(P.similarRules({...payment,currency:'EUR'},[rule]).length,0);assert.equal(P.similarRules({...payment,recipient:'Orange Flex Warsaw'},[rule]).length,0);assert.equal(P.similarRules({...payment,recipient:'NABU CASA* TRIAL HOME'},[{...rule,recipient:'NABU CASA - HA CLOUD'}]).length,1);});
test('explicit linking retains settings and recognizes the new name on future imports',()=>{const target=structuredClone(rule);P.linkContractor(target,payment);assert.equal(target.expected,3700);assert.equal(target.start,'2026-01');assert.equal(P.matches(target,payment),true);P.linkContractor(target,payment);assert.equal(target.aliases.length,1);});
test('merging saved rules preserves all payments and rewires manual assignments',()=>{const s={rules:[rule,{...rule,id:'old',recipient:payment.recipient,start:'2026-05'}],transactions:[{...payment,assignment:'old',month:'2026-04'},{...payment,id:'p2',amount:3700}],imports:[{id:'i1'}]};P.mergeRules(s,'netflix',['old']);assert.equal(s.rules.length,1);assert.equal(s.transactions.length,2);assert.equal(s.transactions[0].assignment,'netflix');assert.equal(s.transactions[0].month,'2026-04');assert.equal(P.allocation(s,s.transactions[1]).rule.id,'netflix');assert.equal(s.imports.length,1);});
test('merge dialog hides new settings and saves alias plus tracked history without a new rule',async()=>{
 const source=fs.readFileSync(path.join(__dirname,'../app/priv/ui.js'),'utf8'),newFields={hidden:false},select={value:'netflix',closest:()=>block},block={dataset:{candidate:'0'},querySelector:q=>q==='[data-merge]'?select:q==='[data-new-fields]'?newFields:(()=>{throw Error('New settings must not be read when merging')})()},elements={modalBody:{querySelectorAll:q=>q==='[data-merge]'?[select]:[block]},saveCandidates:{}},context={P,state:{rules:[structuredClone(rule)],transactions:[],imports:[]},structuredClone,escape:String,money:()=>'',id:()=>'',modal:(_,body)=>context.body=body,$:id=>elements[id],action:fn=>fn(),importOptions:()=>'',appendImport:(next,_,tx)=>next.transactions=P.tracked(tx,next.rules),persist:async next=>context.saved=next,close(){}};
 vm.createContext(context);vm.runInContext(source.slice(source.indexOf('function mergeChoice('),source.indexOf('function download(')),context);context.chooseCandidates([{...payment,accounts:[],currencies:['PLN']}],[],[payment]);assert.match(context.body,/Scal z: Netflix/);select.onchange();assert.equal(newFields.hidden,true);await elements.saveCandidates.onclick();assert.equal(context.saved.rules.length,1);assert.equal(context.saved.rules[0].expected,3700);assert.equal(context.saved.transactions.length,1);
});
