const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('app/priv/ui.js','utf8');
const reader=source.slice(source.indexOf('async function readPdf(file){'),source.indexOf('\nasync function preview(files)'));
function harness(protectedPdf,passwords){let promptCount=0,destroyCount=0;const reasons=[];const doc={numPages:1,getPage:async()=>({getTextContent:async()=>({items:[]})}),destroy:async()=>destroyCount++};
 const context={Uint8Array,Promise,Error,notice(){},P:{rowsFromItems:i=>i,parsePages:()=>({ok:true})},requestPdfPassword:async(name,incorrect)=>{promptCount++;reasons.push({name,incorrect});const result=passwords.shift();if(result instanceof Error)throw result;return result;},pdfLib:{GlobalWorkerOptions:{},PasswordResponses:{INCORRECT_PASSWORD:2},getDocument(){let resolve;const task={promise:new Promise(r=>resolve=r),destroy:async()=>destroyCount++};queueMicrotask(()=>{if(!protectedPdf)resolve(doc);else{const update=value=>{if(value==='correct')resolve(doc);else queueMicrotask(()=>task.onPassword(update,2));};task.onPassword(update,1);}});return task;}}};vm.createContext(context);vm.runInContext(reader,context);return {read:()=>context.readPdf({name:'Bank.pdf',size:10,arrayBuffer:async()=>new ArrayBuffer(2)}),prompts:()=>promptCount,reasons,destroys:()=>destroyCount};}
test('encrypted file asks again after wrong password then reads',async()=>{const h=harness(true,['wrong','correct']);assert.equal((await h.read()).ok,true);assert.equal(h.prompts(),2);assert.equal(h.reasons[0].incorrect,false);assert.equal(h.reasons[1].incorrect,true);assert.equal(h.destroys(),1);});
test('cancel aborts waiting reader without hanging or importing data',async()=>{const h=harness(true,[Error('Anulowano odczyt wyciągu.')]);await assert.rejects(h.read(),/Anulowano/);assert.ok(h.destroys()>=1);});
test('plaintext file reads without password prompt',async()=>{const h=harness(false,[]);assert.equal((await h.read()).ok,true);assert.equal(h.prompts(),0);});
test('password dialog clears entered password and supports cancellation',async()=>{
 const fn=source.slice(source.indexOf('function requestPdfPassword('),source.indexOf('\nasync function readPdf(file)'));
 const controls=new Map();const context={Promise,Error,key:{},state:{},passwordPromptCancel:null,escape:s=>s,modal(){for(const id of ['pdfPassword','pdfPasswordForm','cancelPdfPassword','modal','modalBody','modalFoot'])controls.set(id,{value:'',focus(){},close(){},replaceChildren(){}});},$:id=>controls.get(id)};vm.createContext(context);vm.runInContext(fn,context);
 const pending=context.requestPdfPassword('Bank.pdf');controls.get('pdfPassword').value='bank-secret';controls.get('pdfPasswordForm').onsubmit({preventDefault(){}});assert.equal(await pending,'bank-secret');assert.equal(controls.get('pdfPassword').value,'');assert.equal(context.passwordPromptCancel,null);
 const cancelled=context.requestPdfPassword('Bank.pdf');context.passwordPromptCancel();await assert.rejects(cancelled,/Anulowano/);assert.equal(controls.get('pdfPassword').value,'');
 context.key=null;await assert.rejects(context.requestPdfPassword('Bank.pdf'),/zablokowane/);
});
