import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import vm from 'node:vm';
import * as C from '../app/robisie/core.js';
test('wszystkie moduły renderują dane inwestycji i wspólne numery dokumentów',async()=>{
 const catalog=JSON.parse(await fs.readFile(new URL('../app/robisie/catalog.json',import.meta.url),'utf8'));
 const radios=catalog.map(x=>({value:x.id,checked:false}));
 const nodes=new Map();const node=key=>{if(!nodes.has(key))nodes.set(key,{innerHTML:'',textContent:'',style:{},classList:{toggle(){}},isConnected:true,showModal(){},close(){},querySelectorAll:()=>radios});return nodes.get(key);};
 const context=vm.createContext({console,crypto,structuredClone,FormData:class extends Map{constructor(entries){super(Object.entries(entries));}},setTimeout,clearTimeout,confirm:()=>true,fetch:async()=>({ok:true,json:async()=>catalog}),window:{addEventListener(){},scrollTo(){}},document:{querySelector:node,addEventListener(){}}});
 const source=await fs.readFile(new URL('../app/robisie/app.js',import.meta.url),'utf8');
 const module=new vm.SourceTextModule(source+'\nexport function testLineDialog(){lineDialog("offer");} export function testOffer(){return p().offer;} export function testPicker(){return servicePicker(config.payload.catalog);}' +'\nexport function testRender(row,settings){all=[structuredClone(row)];selected=structuredClone(row);config={payload:settings,revision:1};configBaseline=structuredClone(config);return [...C.MODULES.map(([key])=>key),"catalog","settings"].map(key=>{view=key;return [key,content()];});}',{context});
 await module.link(spec=>{const values=spec.includes('core')?C:{restoreSession:()=>null};const keys=Object.keys(values);return new vm.SyntheticModule(keys,function(){for(const key of keys)this.setExport(key,values[key]);},{context});});
 await module.evaluate();await new Promise(resolve=>setTimeout(resolve,10));
 const payload=C.newProject('Remont testowy','Inwestor testowy');payload.rooms=[{id:'r',name:'Kuchnia',length:4,width:3,height:2.6}];
 payload.offer=[{id:'l',roomId:'r',serviceId:'a',name:'Malowanie',category:'Ściany',unit:'m²',qty:12,price:100,included:true}];payload.works=structuredClone(payload.offer);payload.works[0].done=true;
 payload.purchases=[{id:'x',date:'2026-10-08',shop:'Test',description:'Materiał',invoice:'FV test',amount:100,charge:110,paid:true}];payload.receipts=[{id:'v',date:'2026-10-08',kind:'work',amount:500}];
 const row={id:'p',contract_number:'UUR-RS/2026/10/001',payload,revision:1};
 const results=module.namespace.testRender(row,{catalog,markup:35,company:{name:'ROBISIĘ-FER sp. z o.o.'}});
 assert.equal(results.length,13);for(const [key,html] of results){assert.ok(html.length>50,key);assert.ok(!html.includes('undefined'),key);assert.ok(!html.includes('NaN'),key);}
 assert.ok(results.find(([key])=>key==='overview')[1].includes('WYM-RS/2026/10/001'));
 assert.ok(results.find(([key])=>key==='contract')[1].includes('OFE-RS/2026/10/001/V1'));
 assert.equal(catalog.length,102);
 const catalogHtml=results.find(([key])=>key==='catalog')[1];
 const pickerHtml=module.namespace.testPicker();
 const categories=new Set(catalog.map(x=>x.category));
 assert.equal((catalogHtml.match(/<details /g)||[]).length,categories.size);
 assert.equal((pickerHtml.match(/<details /g)||[]).length,categories.size);
 assert.equal((pickerHtml.match(/type="radio"/g)||[]).length,102);
 assert.ok(!pickerHtml.includes('<select'));assert.ok(!pickerHtml.includes('<details class="service-category" open'));
 module.namespace.testLineDialog();
 const chosen=catalog.at(-1);const radio=radios.at(-1);radio.checked=true;radio.onchange();
 assert.equal(node('#f-name').value,chosen.name);
 assert.equal(node('#f-unit').value,chosen.unit||'');
 assert.equal(node('#f-price').value,C.round(chosen.base*1.35));
 await node('#modal-form').onsubmit({preventDefault(){},target:{serviceId:chosen.id,roomId:'r',name:chosen.name,unit:'m²',qty:'3',price:String(node('#f-price').value),days:'0',hours:'0',note:''}});
 const saved=module.namespace.testOffer().at(-1);
 assert.equal(saved.serviceId,chosen.id);assert.equal(saved.category,chosen.category);assert.equal(saved.qty,3);assert.equal(saved.price,C.round(chosen.base*1.35));
});
