import * as C from './core.js?v=1.0.17';
import * as API from './api.js?v=1.0.17';
import * as PDF from './pdf.js?v=1.0.17';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let all=[],selected=null,view='dashboard',catalog=[],config=null,dirty=false,busy=false,lineFilter='',shopFilter=null,mobileOpen=false,configBaseline=null;
const openRoomGroups=new Set();
const statuses={przygotowanie:'Przygotowanie',oferta:'Oferta',prace:'W realizacji',odbior:'Do odbioru',zakonczona:'Zakończona'};
const defaults=()=>({catalog:structuredClone(catalog),markup:35,company:{name:'ROBISIĘ-FER sp. z o.o.',address:'Rtm. Witolda Pileckiego 18, 43-190 Mikołów',nip:'6351861297',krs:'',representative:'Michał Sobota – prezes zarządu',account:''}});
const p=()=>selected?.payload;
const title=()=>C.MODULES.find(x=>x[0]===view)?.[1]||({dashboard:'Panel administratora',catalog:'Cennik usług',settings:'Dane wykonawcy'}[view]||'Robisię');
const btn=(action,label,cls='',extra='')=>`<button type="button" data-action="${action}" class="${cls}" ${extra}>${label}</button>`;
const input=(name,label,value='',type='text',extra='')=>`<div class="field"><label for="f-${esc(name)}">${label}</label><input id="f-${esc(name)}" name="${esc(name)}" type="${type}" value="${esc(value)}" ${p()?.calculationPrecision==='source'&&type==='number'?extra.replace(/step="[^"]+"/g,'step="any"'):extra}></div>`;
const text=(name,label,value='',extra='')=>`<div class="field"><label for="f-${esc(name)}">${label}</label><textarea id="f-${esc(name)}" name="${esc(name)}" ${extra}>${esc(value)}</textarea></div>`;
const field=(name,label,value,type='text',extra='')=>input(name,label,value,type,`data-field="${name}" ${extra}`);
const metric=(label,value,cls='')=>`<div class="metric ${cls}"><small>${label}</small><strong>${value}</strong></div>`;
const table=(heads,rows)=>`<div class="tablewrap"><table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows||`<tr><td colspan="${heads.length}" class="empty">Brak pozycji</td></tr>`}</tbody></table></div>`;
function logoMarkup(className='',absolute=false){const path='./assets/robisie-logo.png?v='+C.VERSION,src=absolute?new URL(path,window.location.href).href:path;return `<img class="brand-logo ${className}" src="${esc(src)}" alt="Robisię — fachowa ekipa remontowa" width="719" height="297">`;}
const money=C.money;
const date=v=>v?esc(v):'—';
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',5000);}
function checkDirty(){if(!dirty)return true;return confirm('Masz niezapisane zmiany. Opuścić widok bez zapisu?');}
function markDirty(){dirty=true;const bar=$('#save-state');if(bar)bar.textContent='Niezapisane zmiany';}
function roomName(id){return p()?.rooms.find(r=>r.id===id)?.name||'Cała inwestycja';}
function card(content){return `<section class="card">${content}</section>`;}
function documents(){const s=selected;return [['UMOWA',s.contract_number],['WYMIARY',C.attachment(s,'WYM')],['OFERTA',C.attachment(s,'OFE',p().acceptedOffers?.at(-1)?.version||1)],['KALKULACJA KOŃCOWA',C.attachment(s,'KAL-K')],['ROZLICZENIE',C.attachment(s,'ROZ')],['DZIENNIK',C.attachment(s,'DZR')],['PROTOKÓŁ',C.attachment(s,'PZO')],['MATERIAŁY',C.attachment(s,'ZRM')]];}
async function start(){
 try{catalog=await fetch('./catalog.json').then(r=>{if(!r.ok)throw new Error('Nie można wczytać cennika.');return r.json();});
 if(!API.restoreSession()){loginView();return;}await load();
 }catch(e){failure(e);}
}
function loginView(message=''){$('#app').innerHTML=`<div class="login card">${logoMarkup()}<p class="muted">Inwestycje remontowe</p><h1>Logowanie administratora</h1>${message?`<div class="notice error">${esc(message)}</div>`:''}<form id="login">${input('email','Adres e-mail','','email','autocomplete="username" required')}${input('password','Hasło','','password','autocomplete="current-password" required')}<button class="primary" type="submit">Zaloguj się</button></form><p class="muted" style="margin-top:22px">Użyj konta administratora CleanFleet.</p><span class="version">Wersja ${C.VERSION}</span></div>`;}
function failure(e){if(e.code==='PGRST205'||e.code==='PGRST202'||/rs_projects|rs_settings|rs_create_project/.test(e.message)){
 $('#app').innerHTML=`<div class="login card">${logoMarkup()}<h1>Aplikacja czeka na uruchomienie bazy</h1><p>Moduły są przygotowane. Zapisywanie inwestycji będzie dostępne po utworzeniu osobnych tabel Robisię.</p><p class="muted">Zmiana bazy wymaga zatwierdzenia przez administratora. Nie zapisano żadnych danych inwestycji.</p>${btn('reload','Sprawdź ponownie','primary')} ${btn('logout','Wyloguj')}<p class="version" style="margin-top:18px">Wersja ${C.VERSION}</p></div>`;
 }else if(/JWT|token|expired|session|401/i.test(e.message)){API.logout();loginView('Sesja wygasła. Zaloguj się ponownie.');}else{$('#app').innerHTML=`<div class="login card"><h1>Nie udało się wczytać danych</h1><div class="notice error">${esc(e.message)}</div>${btn('reload','Spróbuj ponownie','primary')} ${btn('logout','Wyloguj')}</div>`;}}
async function load(){const admin=await API.rpc('cf_is_admin');if(!admin){API.logout();loginView('Dostęp tylko dla administratora.');return;}
 const [rows,settings]=await Promise.all([API.projects(),API.settings()]);all=rows;config=settings[0]||{payload:defaults(),revision:0};selected=selected?all.find(x=>x.id===selected.id):null;configBaseline=structuredClone(config);dirty=false;render();}
function render(){const side=selected?C.MODULES:[['dashboard','Inwestycje'],['catalog','Cennik usług'],['settings','Dane wykonawcy']];
 $('#app').innerHTML=`<header class="topbar"><div class="row">${btn('menu','Menu','mobile-menu')}${logoMarkup()}<span class="version">Inwestycje remontowe · ${C.VERSION}</span></div><div class="row"><span class="muted" id="save-state">${dirty?'Niezapisane zmiany':'Dane zapisane w bazie'}</span>${btn('logout','Wyloguj','logout')}</div></header><div class="shell"><nav class="${mobileOpen?'open':''}">${selected?btn('back','Wszystkie inwestycje')+'<p class="muted" style="padding:10px">'+esc(p().name)+'<br>'+esc(selected.contract_number)+'</p>':''}${side.map(([key,label])=>btn('nav',label,view===key?'active':'',`data-view="${key}"`)).join('')}${selected?btn('nav','Cennik usług',view==='catalog'?'active':'','data-view="catalog"'):''}</nav><main><div class="toolbar"><div><h1>${title()}</h1><p class="muted">${selected?esc(p().name)+' · '+esc(selected.contract_number):'Robisię — prowadzenie inwestycji'}</p></div><div class="actions">${selected&&view!=='catalog'?btn('print','Generuj PDF')+btn('save','Zapisz zmiany','primary'):view==='dashboard'?btn('new-project','Nowa inwestycja','primary'):btn('save-settings','Zapisz ustawienia','primary')}</div></div><div id="content">${content()}</div>${selected&&view!=='catalog'?`<div class="savebar"><span class="muted">Zmiany zapisujesz przyciskiem „Zapisz zmiany”.</span>${btn('save','Zapisz zmiany','primary')}</div>`:''}</main></div>`;
}
function content(){switch(view){case'dashboard':return dashboard();case'catalog':return catalogView();case'settings':return settingsView();case'overview':return overview();case'data':return dataView();case'rooms':return roomsView();case'offer':return linesView('offer');case'works':return linesView('works');case'summary':return summaryView();case'payments':return paymentsView();case'purchases':return purchasesView();case'journal':return journalView();case'contract':return contractView();case'handover':return handoverView();default:return '';}}
function dashboard(){const active=all.filter(x=>x.payload.status!=='zakonczona'),t=active.map(x=>C.totals(x.payload));return `<div class="metrics">${metric('Aktywne inwestycje',active.length,'gold')}${metric('Wartość aktualnych prac',money(t.reduce((s,x)=>s+x.works.after,0)))}${metric('Wpłaty za prace',money(t.reduce((s,x)=>s+x.paid,0)))}${metric('Pozostałe rozliczenie',money(t.reduce((s,x)=>s+x.remaining,0)))}</div>${card(`<div class="toolbar"><h2>Inwestycje</h2><input id="search-projects" placeholder="Szukaj inwestycji, inwestora lub umowy" aria-label="Szukaj inwestycji" style="max-width:360px"></div><div class="project-list" id="project-list">${projectRows(all)}</div>`)}${card(`<h2>Wymaga uwagi</h2>${all.flatMap(s=>alerts(s).map(a=>`<p>${btn('open',esc(s.payload.name),'',`data-id="${s.id}"`)} <span class="small">${esc(a)}</span></p>`)).join('')||'<p class="muted">Brak zaległych spraw.</p>'}`)}`;}
function projectRows(rows){return rows.map(s=>`<div class="project"><div><h3>${esc(s.payload.name)}</h3><p class="muted" style="margin:0">${esc(s.payload.investor)} · ${esc(s.payload.address||'Adres do uzupełnienia')}<br>${esc(s.contract_number)}</p></div><div class="row"><span class="tag ${esc(s.payload.status)}">${statuses[s.payload.status]||esc(s.payload.status)}</span>${btn('open','Otwórz','',`data-id="${s.id}"`)}${btn('project-delete','Usuń','danger',`data-id="${s.id}"`)}</div></div>`).join('')||'<div class="empty">Dodaj pierwszą inwestycję, aby rozpocząć.</div>';}
function stagePaid(data,id){return (data.receipts||[]).filter(r=>r.kind==='work'&&r.stageId===id).reduce((s,r)=>s+C.number(r.amount),0);}
function alerts(s){const data=s.payload,t=C.totals(data),list=[];if(data.status==='zakonczona')return list;
 if(data.changes?.some(x=>!x.accepted))list.push('Zmiany zakresu oczekują na akceptację.');
 if(data.stages.some(x=>x.due&&x.due<C.today()&&stagePaid(data,x.id)+.01<t.agreed*C.number(x.percent)/100))list.push('Termin płatności etapu upłynął.');
 if(data.purchases.some(x=>!x.paid))list.push('Zakupy oczekują na zapłatę.');if(data.status==='odbior')list.push('Inwestycja czeka na odbiór.');return list;}
function importNotes(){const source=p().sourceImport;if(!source)return '';return card(`<h2>Historia z Numbers</h2><p>${esc(source.fileName)}</p><p class="muted">Arkusze: ${esc(source.sheetNumbers.join(', '))}</p>${source.notes.map(note=>`<p>${esc(note)}</p>`).join('')}`);}
function overview(){const t=C.totals(p());return `${importNotes()}<div class="metrics">${metric('Uzgodniona oferta',money(t.agreed),'gold')}${metric('Aktualna kalkulacja',money(t.works.after))}${metric('Wykonane prace',money(t.works.done))}${metric('Wpłaty za prace',money(t.paid))}${metric('Pozostałe rozliczenie',money(t.remaining))}${metric('Saldo zaliczki materiałowej',money(t.materials.balance))}</div><div class="grid">${C.MODULES.slice(1).map(([key,label])=>`<button class="tile" data-action="nav" data-view="${key}"><strong>${label}</strong><small>${({rooms:p().rooms.length+' pomieszczeń',offer:p().offer.length+' pozycji',works:p().works.length+' pozycji',purchases:p().purchases.length+' zakupów',journal:p().journal.length+' wpisów',payments:p().receipts.length+' wpłat'}[key])||'Otwórz moduł'}</small></button>`).join('')}</div><div style="margin-top:24px">${card('<h2>Dokumenty inwestycji</h2>'+table(['Dokument','Numer'],documents().map(([name,num])=>`<tr><td>${name}</td><td>${esc(num)}</td></tr>`).join('')))}</div>`;}
function dataView(){const d=p();return card(`<div class="grid">${field('name','Nazwa inwestycji',d.name,'text','required')}${field('investor','Imię i nazwisko inwestora',d.investor,'text','required')}${field('investorAddress','Adres zamieszkania inwestora',d.investorAddress)}${field('address','Adres inwestycji',d.address)}${field('phone','Telefon',d.phone,'tel')}${field('email','E-mail',d.email,'email')}${field('pesel','PESEL (opcjonalnie)',d.pesel)}<div class="field"><label for="status">Etap inwestycji</label><select id="status" data-field="status">${Object.entries(statuses).map(([k,v])=>`<option value="${k}" ${k===d.status?'selected':''}>${v}</option>`).join('')}</select></div>${field('startDate','Planowane rozpoczęcie',d.startDate,'date')}${field('endDate','Planowane zakończenie',d.endDate,'date')}</div><p class="muted">Numer umowy ${esc(selected.contract_number)} został nadany podczas tworzenia inwestycji i pozostaje stały.</p>`);}
function roomsView(){const areas=p().rooms.map(C.roomArea);return `<div class="metrics">${metric('Powierzchnia podłóg',C.quantity(areas.reduce((s,x)=>s+x.floor,0))+' m²')}${metric('Powierzchnia sufitów',C.quantity(areas.reduce((s,x)=>s+x.ceiling,0))+' m²')}${metric('Powierzchnia ścian',C.quantity(areas.reduce((s,x)=>s+x.walls,0))+' m²')}</div><div class="actions" style="margin-bottom:20px">${btn('room-add','Dodaj pomieszczenie','primary')}</div><div class="grid">${p().rooms.map(r=>{const a=C.roomArea(r);return `<div class="card room-card"><div class="row"><h3>${esc(r.name)}</h3>${btn('room-edit','Edytuj','',`data-id="${r.id}"`)}</div><p class="muted" style="margin:10px 0">${r.parts?.length?r.parts.length+' części pomieszczenia':`${C.quantity(r.length)} × ${C.quantity(r.width)} × ${C.quantity(r.height)} m`}</p><div class="measure"><span>Podłoga / sufit</span><strong>${C.quantity(a.floor)} m²</strong></div><div class="measure"><span>Ściany po odliczeniach</span><strong>${C.quantity(a.walls)} m²</strong></div><div class="measure"><span>Obwód części</span><strong>${C.quantity(a.perimeter)} m</strong></div></div>`;}).join('')||'<div class="card empty">Dodaj pomieszczenia i ich wymiary.</div>'}</div>`;}
function roomLines(kind,rows){const groups=new Map(p().rooms.map(r=>[r.id,[]]));for(const line of rows){const id=line.roomId||'';if(!groups.has(id))groups.set(id,[]);groups.get(id).push(line);}const isWork=kind==='works';return [...groups].filter(([,items])=>items.length).map(([roomId,items])=>{const key=JSON.stringify([selected.id,kind,roomId]);return `<details class="service-category room-lines" data-room-group="${esc(key)}" ${openRoomGroups.has(key)?'open':''}><summary><span>${esc(roomName(roomId))}</span><small>${items.length} poz.</small></summary><div class="category-items">${table(['Zakres','Praca','Jedn.','Ilość','Cena (zł)','Wartość',...(isWork?['Wykonane']:[]),''],items.map(l=>`<tr><td><input type="checkbox" aria-label="Uwzględnij ${esc(l.name)}" data-line="${l.id}" data-kind="${kind}" data-prop="included" ${l.included!==false?'checked':''}></td><td><span class="line-name">${esc(l.name)}</span><small class="muted">${esc(l.category)}</small></td><td>${esc(l.unit||'—')}</td><td><input class="short" type="number" min="0" step="0.001" aria-label="Ilość ${esc(l.name)}" value="${l.qty}" data-line="${l.id}" data-kind="${kind}" data-prop="qty"></td><td><input class="price" type="number" min="0" step="0.01" aria-label="Cena ${esc(l.name)}" value="${l.price}" data-line="${l.id}" data-kind="${kind}" data-prop="price"></td><td class="num">${money(C.lineValue(l))}</td>${isWork?`<td><input type="checkbox" aria-label="Wykonano ${esc(l.name)}" data-line="${l.id}" data-kind="${kind}" data-prop="done" ${l.done?'checked':''}></td>`:''}<td>${btn('line-edit','Edytuj','',`data-kind="${kind}" data-id="${l.id}"`)}</td></tr>`).join(''))}</div></details>`;}).join('')||'<div class="empty">Brak pozycji. Dodaj pracę do pomieszczenia.</div>';}
function linesView(kind){const isWork=kind==='works',list=p()[kind],t=C.workTotals(list,isWork?p().workDiscount:p().discount),rows=list.filter(l=>!lineFilter||l.roomId===lineFilter);
 return `<div class="metrics">${metric('Przed rabatem',money(t.before))}${metric('Po rabacie',money(t.after),'gold')}${isWork?metric('Wykonane prace',money(t.done)):metric('Szacowany materiał',money(p().materialEstimate))}${metric('Planowany czas',C.quantity(t.hours)+' godz.')}</div>${card(`<div class="toolbar"><div class="row"><select id="line-room" style="width:auto" aria-label="Filtr pomieszczenia"><option value="">Wszystkie pomieszczenia</option>${p().rooms.map(r=>`<option value="${r.id}" ${r.id===lineFilter?'selected':''}>${esc(r.name)}</option>`).join('')}</select>${btn('line-add','Dodaj pracę','primary',`data-kind="${kind}"`)}</div>${!isWork?btn('accept-offer','Zapisz zaakceptowaną ofertę'):''}</div><div class="grid">${field(isWork?'workDiscount':'discount','Rabat (%)',isWork?p().workDiscount:p().discount,'number','min="0" max="100" step="0.01"')}${!isWork?field('materialEstimate','Szacunkowy koszt materiału (zł)',p().materialEstimate,'number','min="0" step="0.01"'):''}</div>${roomLines(kind,rows)}`)}${!isWork?offerHistory():changesView()}`;
}
function offerHistory(){return card(`<h2>Zaakceptowane wersje</h2>${p().acceptedOffers.map(o=>`<div class="history"><div class="row"><strong>${esc(C.attachment(selected,'OFE',o.version))}</strong><span class="muted">${date(o.date)} · ${money(C.workTotals(o.lines,o.discount).after)}</span>${btn('offer-print','PDF / drukuj','',`data-version="${o.version}"`)}</div></div>`).join('')||'<p class="muted">Nie zapisano jeszcze zaakceptowanej oferty.</p>'}`);}
function changesView(){return card(`<h2>Historia zmian zakresu</h2><p class="muted">Zapis obejmuje zmiany ilości, cen i zakresu. Oznaczenie wykonania nie wymaga osobnej akceptacji.</p>${p().changes.map(c=>`<div class="history"><strong>${esc(c.name)}</strong><p class="muted">${date(c.date)} · ${esc(roomName(c.roomId))} · ${money(c.before?C.lineValue(c.before):0)} → ${money(c.after?C.lineValue(c.after):0)}</p><div class="row"><span class="tag">${c.accepted?'Zaakceptowano '+date(c.acceptedDate):'Oczekuje na akceptację'}</span>${!c.accepted?btn('change-accept','Oznacz akceptację inwestora','',`data-id="${c.id}"`):''}</div></div>`).join('')||'<p class="muted">Brak zmian względem zapisanej kalkulacji.</p>'}`);}
function historicSummary(){const rows=p().sourceImport?.summarySnapshot;if(!rows?.length)return '';return card(`<details><summary>Oryginalne podsumowanie z Numbers</summary><p class="muted">Zapis historyczny arkusza 9. Zawiera również pozycje wyłączone z końcowej kalkulacji; nie zwiększa bieżącego rozliczenia.</p>${table(['Kategoria','Praca','Ilość','Wartość ze źródła'],rows.map(r=>`<tr><td>${esc(r['0'])}</td><td>${esc(r['1'])}</td><td>${C.quantity(r['4'])}</td><td>${money(r['5'])}</td></tr>`).join(''))}</details>`);}
function summaryView(){const d=p(),areas=d.rooms.map(C.roomArea),t=C.totals(d);return `<div class="metrics">${metric('Oferta uzgodniona',money(t.agreed))}${metric('Aktualny zakres',money(t.works.after),'gold')}${metric('Zmiana względem oferty',money(t.change))}</div>${card(`<h2>Łączne ilości usług</h2>${table(['Kategoria','Praca','Jednostka','Ilość','Wartość przed rabatem'],C.aggregate(d.works).map(r=>`<tr><td>${esc(r.category)}</td><td>${esc(r.name)}</td><td>${esc(r.unit||'—')}</td><td class="num">${C.quantity(r.qty)}</td><td class="num">${money(r.value)}</td></tr>`).join(''))}<p class="muted" style="margin-top:14px">Rabat kalkulacji końcowej: ${C.quantity(d.workDiscount)}%. Razem po rabacie: ${money(t.works.after)}.</p>`)}${card(`<h2>Powierzchnie</h2>${table(['Rodzaj','Powierzchnia'],[['Podłogi',areas.reduce((s,a)=>s+a.floor,0)],['Sufity',areas.reduce((s,a)=>s+a.ceiling,0)],['Ściany',areas.reduce((s,a)=>s+a.walls,0)]].map(([name,q])=>`<tr><td>${name}</td><td>${C.quantity(q)} m²</td></tr>`).join(''))}`)}${historicSummary()}`;}
function paymentsView(){const d=p(),t=C.totals(d),percent=d.stages.reduce((s,x)=>s+C.number(x.percent),0);return `<div class="metrics">${metric('Wpłaty za prace',money(t.paid))}${metric('Należność za aktualne prace',money(t.works.after))}${metric('Pozostało za prace',money(t.workRemaining))}${metric('Rozliczenie z materiałami',money(t.remaining),'gold')}</div>${percent!==100?'<div class="notice">Suma procentów etapów wynosi '+C.quantity(percent)+'%. Ustaw łącznie 100%.</div>':''}${card(`<div class="toolbar"><h2>Etapy</h2>${btn('stage-add','Dodaj etap')}</div>${table(['Etap','Udział','Planowana kwota','Wpłaty','Termin','Faktura',''],d.stages.map(s=>`<tr><td><strong>${esc(s.name)}</strong><p class="muted" style="margin:4px 0">${esc(s.description)}</p></td><td>${C.quantity(s.percent)}%</td><td class="num">${money(t.agreed*s.percent/100)}</td><td class="num">${money(stagePaid(d,s.id))}</td><td>${date(s.due)}</td><td>${esc(s.invoice)}</td><td>${btn('stage-edit','Edytuj','',`data-id="${s.id}"`)}</td></tr>`).join(''))}<p class="muted" style="margin-top:14px">Etapy są liczone od zaakceptowanej oferty. Zmiana zakresu prac do rozliczenia końcowego: ${money(t.change)}.</p>`)}${card(`<div class="toolbar"><h2>Wpłaty inwestora</h2>${btn('receipt-add','Dodaj wpłatę','primary')}</div>${table(['Data','Rodzaj','Etap','Kwota','Opis',''],d.receipts.map(r=>`<tr><td>${date(r.date)}</td><td>${r.kind==='materials'?'Zaliczka na materiały':'Za prace'}</td><td>${esc(d.stages.find(s=>s.id===r.stageId)?.name||'Rozliczenie końcowe')}</td><td class="num">${money(r.amount)}</td><td>${esc(r.note)}</td><td>${btn('receipt-edit','Edytuj','',`data-id="${r.id}"`)}</td></tr>`).join(''))}`)}`;}
const shopName=value=>String(value??'').trim().replace(/\s+/g,' ');
const shopKey=value=>shopName(value).toLocaleLowerCase('pl');
function purchaseShopFilters(){
 const groups=new Map();for(const item of p().purchases){const key=shopKey(item.shop);if(!groups.has(key))groups.set(key,{name:shopName(item.shop)||'Bez sklepu',count:0,amount:0});const group=groups.get(key);group.count++;group.amount+=C.number(item.amount);}
 if(shopFilter!==null&&!groups.has(shopFilter))shopFilter=null;
 const tile=(key,name,count,amount)=>btn('purchase-shop',`<strong>${esc(name)}</strong><small>Zakupy: ${count}</small><span class="shop-filter-amount" aria-label="Łączna kwota zakupów">${money(amount)}</span>`,`shop-filter${shopFilter===key?' active':''}`,`data-shop="${esc(key??'')}"${key===null?' data-all="true"':''} aria-pressed="${shopFilter===key}"`);
 return `<div class="shop-filters" role="group" aria-label="Filtruj zakupy według sklepu">${tile(null,'Wszystkie',p().purchases.length,[...groups.values()].reduce((sum,g)=>sum+g.amount,0))}${[...groups].sort((a,b)=>a[1].name.localeCompare(b[1].name,'pl')).map(([key,g])=>tile(key,g.name,g.count,g.amount)).join('')}</div>`;
}
function purchasesView(){const t=C.purchaseTotals(p()),filters=purchaseShopFilters(),items=p().purchases.filter(x=>shopFilter===null||shopKey(x.shop)===shopFilter);return `<div class="metrics">${metric('Otrzymane zaliczki',money(t.advances))}${metric('Faktyczne wydatki',money(t.spent))}${metric('Koszt dla inwestora',money(t.charged))}${metric(t.balance>=0?'Do zwrotu inwestorowi':'Dopłata inwestora',money(Math.abs(t.balance)),'gold')}${metric('Faktycznie pozostało',money(t.actualBalance))}${metric('Różnica rozliczenia',money(t.difference))}</div>${card(`<div class="toolbar"><h2>Zakupy materiałów</h2>${btn('purchase-add','Dodaj zakup','primary')}</div>${filters}<p class="muted purchase-filter-info" aria-live="polite">Pokazano ${items.length} z ${p().purchases.length} zakupów. Podsumowanie finansowe obejmuje całą inwestycję.</p>${table(['Data','Sklep','Zakup / dokument','Kwota zakupu','Koszt inwestora','Opłacono',''],items.map(x=>`<tr><td>${date(x.date)}</td><td>${esc(x.shop)}</td><td>${esc(x.description)}<br><span class="muted">${esc(x.invoice)}</span></td><td class="num">${money(x.amount)}</td><td class="num">${money(x.charge)}</td><td>${x.paid?'Tak':'Nie'}</td><td>${btn('purchase-edit','Edytuj','',`data-id="${x.id}"`)}</td></tr>`).join(''))}<p class="muted" style="margin-top:16px">Saldo obejmuje opłacone zakupy. Zaliczki dodajesz w module „Etapy i płatności”. Koszt inwestora można ustalić niezależnie od kwoty zakupu.</p>`)} `;}
function journalView(){return card(`<div class="toolbar"><h2>Wpisy dziennika</h2>${btn('journal-add','Dodaj wpis','primary')}</div>${p().journal.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<div class="history"><div class="toolbar"><strong>${date(x.date)} · ${esc(x.roomId?roomName(x.roomId):'Cała inwestycja')}</strong>${btn('journal-edit','Edytuj','',`data-id="${x.id}"`)}</div><p style="white-space:pre-wrap">${esc(x.description)}</p><p class="muted">Potwierdzenie inwestora: ${x.investorConfirmed?'tak':'brak'} · wykonawcy: ${x.contractorConfirmed?'tak':'brak'}</p></div>`).join('')||'<div class="empty">Brak wpisów w dzienniku.</div>'}`);}
function contractView(){const d=p();return card(`<div class="grid">${field('contractDate','Data umowy',d.contractDate,'date')}${field('contractPlace','Miejsce zawarcia umowy',d.contractPlace)}${field('paymentDays','Termin zapłaty faktury (dni)',d.paymentDays,'number','min="0"')}${field('materialAdvance','Uzgodniona zaliczka na materiały (zł)',d.materialAdvance,'number','min="0" step="0.01"')}${field('terminationPercent','Uzgodniona kara za rozwiązanie (%)',d.terminationPercent,'number','min="0" max="100"')}</div><div class="actions" style="margin-bottom:20px">${btn('contract-edit','Edytuj pełną treść umowy')}${btn('contract-generate','Wstaw treść z aktualnych danych')}</div><div class="contract-preview"><pre class="document">${esc(PDF.contractParts(d.contractText||C.contractTemplate(selected,config.payload)).text)}</pre><div class="contract-preview-signatures"><span>${esc(PDF.contractParts(d.contractText||C.contractTemplate(selected,config.payload)).contractor)}<br>Data i podpis Wykonawcy</span><span>${esc(PDF.contractParts(d.contractText||C.contractTemplate(selected,config.payload)).investor)}<br>Data i podpis Inwestora</span></div></div><p class="muted">Po edycji pełnej treści zmiany danych nie nadpisują jej automatycznie. „Wstaw treść z aktualnych danych” przygotowuje nowy tekst.</p>`);}
function handoverView(){const d=p(),h=d.handover;return card(`<div class="grid">${input('handover.date','Data odbioru',h.date,'date','data-handover="date"')}${input('handover.receiver','Odbiorca (jeśli inny niż inwestor)',h.receiver,'text','data-handover="receiver"')}</div><label class="inline-check"><input type="checkbox" data-handover="accepted" ${h.accepted?'checked':''}> Prace zaakceptowane przez inwestora</label><div style="margin-top:16px">${text('handover.notes','Uwagi do wykonanych prac',h.notes,'data-handover="notes"')}</div><p class="muted">Dokument ${esc(C.attachment(selected,'PZO'))} zawiera dane inwestycji, zakres wykonanych prac i miejsce na podpisy.</p>${btn('finish','Oznacz inwestycję jako zakończoną','primary')}`);}
const defaultUnits=['m²','mb','szt.','godz.','kpl','m','m³'];
const customUnitValue='__robisie_custom_unit__';
const cleanUnit=value=>String(value||'').trim().replace(/\s+/g,' ');
function unitOptions(current=''){const values=[...defaultUnits,...(config.payload.units||[]),...config.payload.catalog.map(x=>x.unit),...all.flatMap(x=>[...(x.payload.offer||[]),...(x.payload.works||[])].map(l=>l.unit)),current];const result=[],seen=new Set();for(const value of values){const unit=cleanUnit(value),key=unit.toLocaleLowerCase('pl');if(unit&&!seen.has(key)){seen.add(key);result.push(unit);}}return result;}
function unitField(current='',required=true){const options=unitOptions(current),value=options.find(x=>x.toLocaleLowerCase('pl')===cleanUnit(current).toLocaleLowerCase('pl'))||'';return `<div class="field"><label for="f-unit">Jednostka</label><select id="f-unit" name="unit" ${required?'required':''}><option value="">Wybierz jednostkę</option>${options.map(x=>`<option value="${esc(x)}" ${x===value?'selected':''}>${esc(x)}</option>`).join('')}<option value="${customUnitValue}">Dodaj własną…</option></select></div><div id="custom-unit-field" hidden>${input('customUnit','Własna jednostka','','text','disabled maxlength="40"')}<p class="muted">Po zapisaniu będzie dostępna na liście przy kolejnych pracach.</p></div>`;}
function bindUnitField(){const select=$('#f-unit'),custom=$('#f-customUnit');select.onchange=()=>{const own=select.value===customUnitValue;$('#custom-unit-field').hidden=!own;custom.disabled=!own;custom.required=own;if(own)custom.focus();};}
function chooseServiceUnit(value){const select=$('#f-unit'),unit=cleanUnit(value),option=Array.from(select.options).find(x=>x.value.toLocaleLowerCase('pl')===unit.toLocaleLowerCase('pl'));select.value=option?option.value:unit?customUnitValue:'';$('#f-customUnit').value=option?'':unit;select.onchange();}
function readUnit(fd,required=true){const unit=cleanUnit(fd.get('unit')===customUnitValue?fd.get('customUnit'):fd.get('unit'));if(required&&!unit)throw new Error('Wybierz jednostkę lub dodaj własną.');if(unit.length>40||unit===customUnitValue)throw new Error('Jednostka może mieć najwyżej 40 znaków.');return unit;}
async function rememberUnit(unit){if(!unit||[...defaultUnits,...(configBaseline.payload.units||[])].some(x=>x.toLocaleLowerCase('pl')===unit.toLocaleLowerCase('pl')))return;const payload=structuredClone(configBaseline.payload);payload.units=[...(payload.units||[]),unit];const result=await API.saveSettings(payload,configBaseline.revision),row=Array.isArray(result)?result[0]:result;config.payload.units=structuredClone(row.payload.units);config.revision=row.revision;configBaseline=structuredClone(row);}
function serviceGroups(services){const groups=new Map();for(const service of services){const category=service.category||'Pozostałe prace';if(!groups.has(category))groups.set(category,[]);groups.get(category).push(service);}return [...groups];}
function serviceCategories(services,rows){return serviceGroups(services).map(([category,items])=>`<details class="service-category"><summary><span>${esc(category)}</span><small>${items.length} poz.</small></summary><div class="category-items">${rows(items)}</div></details>`).join('');}
function servicePicker(services){return `<fieldset class="service-picker"><legend>Usługa z cennika</legend><p class="muted">Rozwiń kategorię i wybierz konkretną pracę.</p>${serviceCategories(services,items=>items.map(x=>`<label class="service-option"><input type="radio" name="serviceId" value="${esc(x.id)}" required><span><strong>${esc(x.name)}</strong><small>${esc(x.unit||'Jednostka do ustalenia')}</small></span><span class="service-price">${money(x.base*(1+C.number(config.payload.markup)/100))}</span></label>`).join(''))||'<p class="muted">Cennik jest pusty. Dodaj usługę w cenniku.</p>'}</fieldset>`;}
function catalogView(){const s=config.payload;return card(`<div class="grid">${input('markup','Podwyższenie ceny bazowej (%)',s.markup,'number','data-config="markup" min="0" step="0.01"')}</div><div class="toolbar"><p class="muted">Zmiany cennika dotyczą nowych pozycji. Ceny już zapisane w inwestycjach pozostają bez zmian.</p>${btn('service-add','Dodaj usługę')}</div>${serviceCategories(s.catalog,items=>table(['Usługa','Jedn.','Cena bazowa','Cena po podwyższeniu',''],items.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.unit||'do ustalenia')}</td><td class="num">${money(x.base)}</td><td class="num">${money(x.base*(1+C.number(s.markup)/100))}</td><td>${btn('service-edit','Edytuj','',`data-id="${esc(x.id)}"`)}</td></tr>`).join('')))}<p class="muted" style="margin-top:16px">Jednostki nie były zdefiniowane w cenniku źródłowym. Ustaw je tutaj lub wybieraj podczas dodawania pracy.</p>`);}
function settingsView(){const c=config.payload.company;return card(`<div class="grid">${Object.entries({name:'Nazwa wykonawcy',address:'Adres',nip:'NIP',krs:'KRS',representative:'Osoba reprezentująca',account:'Numer rachunku'}).map(([k,v])=>input(k,v,c[k]||'','text',`data-company="${k}"`)).join('')}</div><p class="muted">Dane wykonawcy trafiają do generowanych dokumentów. Uzupełnij KRS i rachunek przed przygotowaniem umowy.</p>`);}
function modal(title,body,onSubmit,remove,layout='',submitLabel='Zapisz'){const d=$('#dialog');d.className=layout;d.innerHTML=`<header><h2>${title}</h2>${btn('close','Zamknij')}</header><form id="modal-form">${body}<footer>${remove?btn('delete','Usuń','danger'):''}${btn('close','Anuluj')}<button type="submit" class="primary">${esc(submitLabel)}</button></footer></form>`;
 let submitting=false;$('#modal-form').onsubmit=async e=>{e.preventDefault();if(submitting)return;submitting=true;try{await onSubmit(new FormData(e.target));d.close();render();}catch(err){toast(err.message);}finally{submitting=false;}};d.oncancel=()=>{};d.showModal();d.scrollTop=0;if(remove)d.querySelector('[data-action="delete"]').onclick=()=>{if(confirm('Usunąć tę pozycję?')){try{remove();markDirty();d.close();render();}catch(err){toast(err.message);}}};
}
function roomDialog(id){const r=p().rooms.find(x=>x.id===id)||{id:C.uid(),name:'',length:0,width:0,height:2.6,openings:0,sharedWalls:0};
 modal(id?'Edytuj pomieszczenie':'Nowe pomieszczenie',input('name','Nazwa',r.name,'text','required')+`<div class="grid">${input('length','Długość (m)',r.length,'number','min="0" step="0.001" required')}${input('width','Szerokość (m)',r.width,'number','min="0" step="0.001" required')}${input('height','Wysokość (m)',r.height,'number','min="0.01" step="0.001" required')}${input('openings','Odliczenie okien i drzwi (m²)',r.openings,'number','min="0" step="0.001"')}${input('sharedWalls','Odliczenie wspólnych ścian części (m²)',r.sharedWalls,'number','min="0" step="0.001"')}</div>`+text('parts','Dodatkowe części pomieszczenia: długość; szerokość; wysokość (jedna część w wierszu)',r.parts?.slice(1).map(x=>`${x.length}; ${x.width}; ${x.height}`).join('\n')||'')+'<p class="muted">Dla holu lub nieregularnego pomieszczenia dodaj prostokątne części. Powierzchnie są sumowane. Wspólne ściany odliczasz ręcznie. Zmiana pomiarów nie nadpisuje ilości w zaakceptowanej ofercie.</p>',fd=>{
 const item={...r,name:fd.get('name'),length:C.number(fd.get('length')),width:C.number(fd.get('width')),height:C.number(fd.get('height')),openings:C.number(fd.get('openings')),sharedWalls:C.number(fd.get('sharedWalls'))};
 item.parts=[{length:item.length,width:item.width,height:item.height}];const extra=String(fd.get('parts')).trim();if(extra)for(const row of extra.split('\n')){const parts=row.split(';').map(C.number);if(parts.length!==3||parts.some(x=>x<=0))throw new Error('Każda dodatkowa część musi mieć trzy dodatnie wymiary oddzielone średnikiem.');item.parts.push({length:parts[0],width:parts[1],height:parts[2]});}
 if(item.parts.length===1)delete item.parts;if(id)p().rooms=p().rooms.map(x=>x.id===id?item:x);else p().rooms.push(item);markDirty();
 },id?()=>{if([...p().offer,...p().works].some(x=>x.roomId===id))throw new Error('Pomieszczenie ma przypisane prace. Usuń je lub zmień przypisanie przed usunięciem pomieszczenia.');p().rooms=p().rooms.filter(x=>x.id!==id);}:null);
}
function lineDialog(kind,id){const l=p()[kind].find(x=>x.id===id);const services=config.payload.catalog;const r=l?.roomId||lineFilter||p().rooms[0]?.id||'';
 const select=(name,label,options,value)=>`<div class="field"><label for="f-${name}">${label}</label><select id="f-${name}" name="${name}">${options.map(([k,v])=>`<option value="${esc(k)}" ${k===value?'selected':''}>${esc(v)}</option>`).join('')}</select></div>`;
 const fields=select('roomId','Pomieszczenie',[['','Cała inwestycja'],...p().rooms.map(r=>[r.id,r.name])],r)+input('name','Nazwa pracy',l?.name||'','text','required')+unitField(l?.unit||'')+`<div class="grid">${input('qty','Ilość',l?.qty||0,'number','min="0" step="0.001" required')}${input('price','Cena jednostkowa (zł)',l?.price??0,'number','min="0" step="0.01" required')}${input('days','Planowana liczba dni',l?.days||0,'number','min="0" step="0.01"')}${input('hours','Planowana liczba godzin',l?.hours||0,'number','min="0" step="0.01"')}</div><div class="row" style="margin-bottom:16px">${btn('use-area','Wstaw powierzchnię ścian','','data-area="walls"')}${btn('use-area','Wstaw powierzchnię podłogi','','data-area="floor"')}${btn('use-area','Wstaw powierzchnię sufitu','','data-area="ceiling"')}${btn('use-area','Wstaw obwód','','data-area="perimeter"')}</div>`+text('note','Uwagi',l?.note||'');
 const body=l?fields:`<div class="line-layout"><div class="line-services">${servicePicker(services)}</div><div class="line-fields">${fields}</div></div>`;
 modal(id?'Edytuj pracę':'Dodaj pracę',body,async fd=>{
 const service=services.find(x=>x.id===fd.get('serviceId'));if(!l&&!service)throw new Error('Rozwiń kategorię i wybierz pracę z cennika.');const unit=readUnit(fd);await rememberUnit(unit);const item={...(l||{}),id:l?.id||C.uid(),serviceId:l?.serviceId||service.id,category:l?.category||service.category,roomId:fd.get('roomId'),name:fd.get('name'),unit,qty:C.number(fd.get('qty')),price:C.number(fd.get('price')),days:C.number(fd.get('days')),hours:C.number(fd.get('hours')),note:fd.get('note'),included:l?.included!==false,done:l?.done||false};if(l)p()[kind]=p()[kind].map(x=>x.id===id?item:x);else p()[kind].push(item);markDirty();
 },id?()=>{p()[kind]=p()[kind].filter(x=>x.id!==id);}:null,l?'':'line-modal');
 bindUnitField();
 for(const radio of $('#dialog').querySelectorAll('input[name="serviceId"]')){radio.oninvalid=()=>{$('#dialog').querySelector('input[name="serviceId"]').closest('details').open=true;};radio.onchange=()=>{if(!radio.checked)return;const service=services.find(x=>x.id===radio.value);$('#f-name').value=service.name;chooseServiceUnit(service.unit);$('#f-price').value=C.round(service.base*(1+C.number(config.payload.markup)/100));};}
}
function receiptDialog(id){const x=p().receipts.find(x=>x.id===id)||{id:C.uid(),date:C.today(),amount:0,kind:'work',stageId:'',note:''};modal(id?'Edytuj wpłatę':'Nowa wpłata',`<div class="grid">${input('date','Data',x.date,'date','required')}${input('amount','Kwota (zł)',x.amount,'number','min="0.01" step="0.01" required')}</div><div class="field"><label>Rodzaj</label><select name="kind"><option value="work" ${x.kind==='work'?'selected':''}>Za prace</option><option value="materials" ${x.kind==='materials'?'selected':''}>Zaliczka na materiały</option></select></div><div class="field"><label>Etap</label><select name="stageId"><option value="">Rozliczenie końcowe / bez etapu</option>${p().stages.map(s=>`<option value="${s.id}" ${s.id===x.stageId?'selected':''}>${esc(s.name)}</option>`).join('')}</select></div>${text('note','Opis / numer dokumentu',x.note)}`,fd=>{const item={...x,...Object.fromEntries(fd),amount:C.number(fd.get('amount'))};if(item.kind==='materials')item.stageId='';if(id)p().receipts=p().receipts.map(r=>r.id===id?item:r);else p().receipts.push(item);markDirty();},id?()=>p().receipts=p().receipts.filter(r=>r.id!==id):null);}
function purchaseDialog(id){const x=p().purchases.find(x=>x.id===id)||{id:C.uid(),date:C.today(),shop:'',description:'',invoice:'',amount:0,charge:0,paid:true};modal(id?'Edytuj zakup':'Nowy zakup',`<div class="grid">${input('date','Data',x.date,'date','required')}${input('shop','Sklep',x.shop,'text','required')}${input('amount','Rzeczywista kwota zakupu (zł)',x.amount,'number','min="0" step="0.01" required')}${input('charge','Koszt przypisany inwestorowi (zł)',x.charge,'number','min="0" step="0.01" required')}${input('invoice','Numer faktury / paragonu',x.invoice)}</div>${text('description','Opis zakupu',x.description,'required')}<label class="inline-check"><input type="checkbox" name="paid" ${x.paid?'checked':''}> Zakup opłacony</label>`,fd=>{const item={...x,...Object.fromEntries(fd),amount:C.number(fd.get('amount')),charge:C.number(fd.get('charge')),paid:fd.has('paid')};if(id)p().purchases=p().purchases.map(r=>r.id===id?item:r);else p().purchases.push(item);markDirty();},id?()=>p().purchases=p().purchases.filter(r=>r.id!==id):null);if(!id)$('#f-amount').oninput=()=>{$('#f-charge').value=$('#f-amount').value;};}
function stageDialog(id){const x=p().stages.find(x=>x.id===id)||{id:C.uid(),name:'',percent:0,description:'',due:'',invoice:''};modal(id?'Edytuj etap':'Nowy etap',input('name','Nazwa',x.name,'text','required')+`<div class="grid">${input('percent','Udział (%)',x.percent,'number','min="0" max="100" step="0.01" required')}${input('due','Termin płatności',x.due,'date')}${input('invoice','Numer / data faktury',x.invoice)}</div>`+text('description','Zakres etapu',x.description),fd=>{const item={...x,...Object.fromEntries(fd),percent:C.number(fd.get('percent'))};if(id)p().stages=p().stages.map(r=>r.id===id?item:r);else p().stages.push(item);markDirty();},id?()=>{if(p().receipts.some(r=>r.stageId===id))throw new Error('Najpierw zmień przypisanie wpłat tego etapu.');p().stages=p().stages.filter(r=>r.id!==id);}:null);}
function journalDialog(id){const x=p().journal.find(x=>x.id===id)||{id:C.uid(),date:C.today(),roomId:'',description:'',investorConfirmed:false,contractorConfirmed:false};modal(id?'Edytuj wpis':'Nowy wpis dziennika',input('date','Data',x.date,'date','required')+`<div class="field"><label>Pomieszczenie</label><select name="roomId"><option value="">Cała inwestycja</option>${p().rooms.map(r=>`<option value="${r.id}" ${r.id===x.roomId?'selected':''}>${esc(r.name)}</option>`).join('')}</select></div>`+text('description','Opis prac / ustaleń',x.description,'required')+`<label class="inline-check"><input type="checkbox" name="investorConfirmed" ${x.investorConfirmed?'checked':''}> Potwierdzone przez inwestora</label><label class="inline-check"><input type="checkbox" name="contractorConfirmed" ${x.contractorConfirmed?'checked':''}> Potwierdzone przez wykonawcę</label>`,fd=>{const item={...x,...Object.fromEntries(fd),investorConfirmed:fd.has('investorConfirmed'),contractorConfirmed:fd.has('contractorConfirmed')};if(id)p().journal=p().journal.map(r=>r.id===id?item:r);else p().journal.push(item);markDirty();},id?()=>p().journal=p().journal.filter(r=>r.id!==id):null);}
function serviceDialog(id){const x=config.payload.catalog.find(x=>x.id===id)||{id:C.uid(),name:'',category:'',base:0,unit:''};modal(id?'Edytuj usługę':'Nowa usługa',input('name','Nazwa usługi',x.name,'text','required')+input('category','Kategoria',x.category,'text','required')+unitField(x.unit,false)+input('base','Cena bazowa (zł)',x.base,'number','min="0" step="0.01" required'),async fd=>{const unit=readUnit(fd,false);await rememberUnit(unit);const values=Object.fromEntries(fd);delete values.customUnit;const item={...x,...values,unit,base:C.number(fd.get('base'))};if(id)config.payload.catalog=config.payload.catalog.map(s=>s.id===id?item:s);else config.payload.catalog.push(item);markDirty();});bindUnitField();}
async function removeProject(id){if(busy)return;const project=all.find(x=>x.id===id);if(!project)return;if(!confirm(`Usunąć inwestycję „${project.payload.name}” (${project.contract_number})?\n\nUsunięte zostaną jej pomieszczenia, prace, rozliczenia i historia. Tej operacji nie można cofnąć. Numer umowy nie zostanie użyty ponownie.`))return;busy=true;try{const deleted=await API.deleteProject(project);if(deleted!==project.id)throw new Error('Nie potwierdzono usunięcia inwestycji. Odśwież listę.');all=all.filter(x=>x.id!==id);if(selected?.id===id){selected=null;view='dashboard';dirty=false;}render();toast('Usunięto inwestycję.');}finally{busy=false;}}
async function save(){if(busy)return;busy=true;try{const data=structuredClone(p()),previous=all.find(s=>s.id===selected.id)?.payload;
 if(previous&&!(previous.works.length===0&&data.acceptedOffers.length>previous.acceptedOffers.length)){const normalize=rows=>rows.map(({done,...rest})=>rest);const changed=C.changeRecord(normalize(previous.works),normalize(data.works));data.changes.push(...changed);}
 const row=await API.saveProject(selected,data);selected=Array.isArray(row)?row[0]:row;all=all.map(x=>x.id===selected.id?structuredClone(selected):x);dirty=false;render();toast('Zapisano zmiany.');
 }finally{busy=false;}}
async function saveConfig(){if(busy)return;busy=true;try{const row=await API.saveSettings(config.payload,config.revision);config=Array.isArray(row)?row[0]:row;configBaseline=structuredClone(config);dirty=false;render();toast('Zapisano ustawienia.');}finally{busy=false;}}
function pdfDialog(){if(dirty){toast('Zapisz zmiany przed przygotowaniem dokumentu.');return;}const initial=view==='overview'?PDF.MODULES.map(([key])=>key):[view];modal('Wybierz części dokumentu PDF',`<p class="muted">Wybrane części zostaną połączone w jeden dokument. Każda rozpocznie się na nowej stronie.</p><div class="row" style="margin-bottom:16px">${btn('pdf-all','Zaznacz wszystkie')}${btn('pdf-none','Odznacz wszystkie')}</div><div class="pdf-choices">${PDF.MODULES.map(([key,label])=>`<label class="pdf-choice"><input type="checkbox" name="pdfModule" value="${key}" ${initial.includes(key)?'checked':''}><span>${esc(label)}</span></label>`).join('')}</div>`,fd=>{const modules=fd.getAll('pdfModule');if(!modules.length)throw new Error('Wybierz przynajmniej jedną część dokumentu.');printDoc(view,null,modules);},null,'','Otwórz dokument PDF');}
function printDoc(which=view,offer,modules){if(dirty)throw new Error('Zapisz zmiany przed przygotowaniem dokumentu.');const logoUrl=new URL('./assets/robisie-logo.png?v='+C.VERSION,window.location.href).href,html=PDF.buildDocument(selected,config.payload,{modules:modules||[which==='overview'?'data':which],logoUrl,offer});const win=window.open('','_blank');if(!win)throw new Error('Zezwól na otwarcie dokumentu w nowej karcie.');win.document.write(html);win.document.close();}
document.addEventListener('submit',async e=>{if(e.target.id!=='login')return;e.preventDefault();const f=new FormData(e.target),b=e.target.querySelector('button');b.disabled=true;try{await API.login(f.get('email'),f.get('password'));await load();}catch(err){loginView(err.message);}});
document.addEventListener('input',e=>{const el=e.target;
 if(el.id==='search-projects'){$('#project-list').innerHTML=projectRows(all.filter(x=>JSON.stringify([x.payload.name,x.payload.investor,x.payload.address,x.contract_number]).toLocaleLowerCase('pl').includes(el.value.toLocaleLowerCase('pl'))));return;}
 if(el.dataset.field){p()[el.dataset.field]=el.type==='number'?C.number(el.value):el.value;markDirty();}
 if(el.dataset.handover){p().handover[el.dataset.handover]=el.type==='checkbox'?el.checked:el.value;markDirty();}
 if(el.dataset.config){config.payload[el.dataset.config]=C.number(el.value);markDirty();}
 if(el.dataset.company){config.payload.company[el.dataset.company]=el.value;markDirty();}
 if(el.dataset.line){const l=p()[el.dataset.kind].find(x=>x.id===el.dataset.line);l[el.dataset.prop]=el.type==='checkbox'?el.checked:C.number(el.value);markDirty();}
});
document.addEventListener('toggle',e=>{const el=e.target,key=el.dataset?.roomGroup;if(!key||!el.isConnected)return;if(el.open)openRoomGroups.add(key);else openRoomGroups.delete(key);},true);
document.addEventListener('change',e=>{if(e.target.id==='line-room'){lineFilter=e.target.value;render();}else if(e.target.dataset.line||e.target.dataset.field==='discount'||e.target.dataset.field==='workDiscount')render();});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,id=b.dataset.id;try{
 if(a==='close'){$('#dialog').close();return;}if(a==='delete')return;
 if(a==='menu'){mobileOpen=!mobileOpen;$('nav').classList.toggle('open',mobileOpen);return;}
 if(a==='logout'){if(!checkDirty())return;API.logout();selected=null;dirty=false;loginView();return;}
 if(a==='reload'){await load();return;}
 if(a==='nav'||a==='back'||a==='open'){if(!checkDirty())return;if(dirty){if(selected)selected=structuredClone(all.find(x=>x.id===selected.id));config=structuredClone(configBaseline);}dirty=false;mobileOpen=false;if(a==='open'){selected=structuredClone(all.find(x=>x.id===id));view='overview';}else if(a==='back'){selected=null;view='dashboard';}else view=b.dataset.view;lineFilter='';shopFilter=null;render();window.scrollTo(0,0);return;}
 if(a==='new-project'){modal('Nowa inwestycja',input('name','Nazwa inwestycji','','text','required')+input('investor','Imię i nazwisko inwestora','','text','required')+input('date','Data nadania numeru umowy',C.today(),'date','required')+'<p class="muted">Numer zostanie nadany w bazie według schematu UUR-RS/rok/miesiąc/kolejny numer w danym miesiącu.</p>',async fd=>{const row=await API.createProject(C.newProject(fd.get('name'),fd.get('investor'),fd.get('date')),fd.get('date'));selected=Array.isArray(row)?row[0]:row;all.unshift(structuredClone(selected));view='data';dirty=false;});return;}
 if(a==='project-delete'){b.disabled=true;await removeProject(id);return;}
 if(a==='save'){b.disabled=true;await save();return;}if(a==='save-settings'){b.disabled=true;await saveConfig();return;}
 if(a==='room-add'||a==='room-edit'){roomDialog(id);return;}
 if(a==='line-add'||a==='line-edit'){lineDialog(b.dataset.kind,id);return;}
 if(a==='use-area'){const room=p().rooms.find(r=>r.id===$('#f-roomId').value);if(!room){toast('Wybierz pomieszczenie.');return;}$('#f-qty').value=C.roomArea(room)[b.dataset.area];$('#f-unit').value=b.dataset.area==='perimeter'?'mb':'m²';return;}
 if(a==='receipt-add'||a==='receipt-edit'){receiptDialog(id);return;}
 if(a==='purchase-shop'){shopFilter=b.dataset.all==='true'?null:b.dataset.shop;render();return;}
 if(a==='purchase-add'||a==='purchase-edit'){purchaseDialog(id);return;}
 if(a==='stage-add'||a==='stage-edit'){stageDialog(id);return;}
 if(a==='journal-add'||a==='journal-edit'){journalDialog(id);return;}
 if(a==='service-add'||a==='service-edit'){serviceDialog(id);return;}
 if(a==='accept-offer'){if(!p().offer.some(l=>l.included!==false&&l.qty>0))throw new Error('Dodaj przynajmniej jedną pracę z ilością.');if(!confirm('Zapisać tę ofertę jako zaakceptowaną przez inwestora? Jej treść pozostanie w historii.'))return;
 p().acceptedOffers.push({version:p().acceptedOffers.length+1,date:C.today(),lines:structuredClone(p().offer),discount:p().discount,materialEstimate:p().materialEstimate});
 if(!p().works.length){p().works=structuredClone(p().offer);p().workDiscount=p().discount;}p().status='oferta';markDirty();await save();return;}
 if(a==='change-accept'){const change=p().changes.find(x=>x.id===id);change.accepted=true;change.acceptedDate=C.today();markDirty();await save();return;}
 if(a==='contract-edit'){modal('Treść umowy',text('body','Treść',p().contractText||C.contractTemplate(selected,config.payload),'style="min-height:50vh"'),fd=>{p().contractText=fd.get('body');markDirty();});return;}
 if(a==='contract-generate'){if(p().contractText&&!confirm('Zastąpić edytowaną treść umowy tekstem z aktualnych danych?'))return;p().contractText=C.contractTemplate(selected,config.payload);markDirty();render();return;}
 if(a==='finish'){if(!p().handover.date)throw new Error('Uzupełnij datę odbioru.');if(!p().handover.accepted)throw new Error('Prace muszą być zaakceptowane przed zakończeniem inwestycji.');p().status='zakonczona';markDirty();await save();return;}
 if(a==='pdf-all'||a==='pdf-none'){for(const checkbox of $('#dialog').querySelectorAll('input[name="pdfModule"]'))checkbox.checked=a==='pdf-all';return;}
 if(a==='print'){pdfDialog();return;}if(a==='offer-print'){printDoc('offer',p().acceptedOffers.find(x=>x.version===Number(b.dataset.version)));return;}
 }catch(err){toast(err.message);}finally{if(b.isConnected)b.disabled=false;}});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
start();
