
import {createClient} from 'npm:@supabase/supabase-js@2.57.4';
import {ImapFlow} from 'npm:imapflow@2.2.1';

const URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const OPENAI=Deno.env.get('OPENAI_API_KEY')!;
const db=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
const enc=new TextEncoder();
const MAX=8*1024*1024;
const TZ='Europe/Warsaw';

function json(v:any,s=200){return new Response(JSON.stringify(v),{status:s,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}})}
function clean(v:any,n=300){return String(v??'').trim().slice(0,n)}
function norm(v:any){return clean(v,500).normalize('NFKC').toLocaleLowerCase('pl-PL')}
function b64(bytes:Uint8Array){let out='';for(let i=0;i<bytes.length;i+=0x8000)out+=String.fromCharCode(...bytes.subarray(i,Math.min(bytes.length,i+0x8000)));return btoa(out)}
function unb64(v:string){return Uint8Array.from(atob(v.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0))}
function dateOk(v:any){const s=clean(v,20);if(!/^20\d{2}-\d{2}-\d{2}$/.test(s))return null;const d=new Date(s+'T12:00:00Z');return Number.isFinite(d.getTime())?s:null}
function localParts(iso:string){const d=new Date(iso);const p=new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(d);const g=(t:string)=>p.find(x=>x.type===t)?.value||'';return{date:g('year')+'-'+g('month')+'-'+g('day'),time:g('hour')+':'+g('minute')}}
function zoneOffsetMs(at:Date){const p=new Intl.DateTimeFormat('en-US',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(at);const g=(t:string)=>Number(p.find(x=>x.type===t)?.value||0);return Date.UTC(g('year'),g('month')-1,g('day'),g('hour'),g('minute'),g('second'))-at.getTime()}
function localIso(date:string,time:string){const guess=new Date(date+'T'+time+':00Z');let off=zoneOffsetMs(guess);let out=new Date(guess.getTime()-off);const off2=zoneOffsetMs(out);if(off2!==off)out=new Date(guess.getTime()-off2);return out.toISOString()}
function calcRemind(due:string,mode:string,oldDue?:string|null,oldCustom?:string|null){if(mode==='custom'&&oldDue&&oldCustom){const diff=new Date(oldDue).getTime()-new Date(oldCustom).getTime();if(Number.isFinite(diff))return new Date(new Date(due).getTime()-diff).toISOString()}const days=mode==='day_1'?1:mode==='day_2'?2:mode==='day_3'?3:0;return days?new Date(new Date(due).getTime()-days*86400000).toISOString():due}
function parts(node:any,out:any[]=[]){if(!node)return out;const name=node.dispositionParameters?.filename||node.parameters?.name;if(node.childNodes?.length){for(const c of node.childNodes)parts(c,out)}else if(name&&/\.pdf$/i.test(String(name))&&/^[1-9]\d*(\.[1-9]\d*)*$/.test(node.part||'1'))out.push({part:node.part||'1',filename:clean(name,180).split(/[\\/]/).at(-1),size:Number(node.size)||0});return out}
async function credential(cipher:string,uid:string){const raw=await crypto.subtle.importKey('raw',enc.encode(SERVICE),'HKDF',false,['deriveKey']);const key=await crypto.subtle.deriveKey({name:'HKDF',hash:'SHA-256',salt:enc.encode('CleanFleet/Mail/v1'),info:enc.encode('mail-credentials-v1')},raw,{name:'AES-GCM',length:256},false,['decrypt']);const bytes=unb64(cipher);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes.slice(0,12)},key,bytes.slice(12));const state=JSON.parse(new TextDecoder().decode(plain));if(state.userId!==uid||state.scope!=='mail-stored')throw new Error('Zapisane połączenie poczty jest nieważne.');return state}
async function readPdf(client:any,uid:number,p:any){if(p.size>MAX)throw new Error('PDF przekracza 8 MB.');const d=await client.download(uid,p.part,{uid:true,maxBytes:MAX+1});const chunks:Uint8Array[]=[];let size=0;for await(const x of d.content){const u=new Uint8Array(x);size+=u.length;if(size>MAX)throw new Error('PDF przekracza 8 MB.');chunks.push(u)}const bytes=new Uint8Array(size);let o=0;for(const x of chunks){bytes.set(x,o);o+=x.length}return bytes}
function outputText(v:any){return typeof v?.output_text==='string'?v.output_text:(v?.output||[]).flatMap((o:any)=>o.content||[]).filter((c:any)=>c.type==='output_text').map((c:any)=>c.text).join('')}
async function analyze(bytes:Uint8Array,filename:string,ctx:any){const prompt=['Odczytaj fakturę PDF dla przypomnienia płatności.','Zwróć wyłącznie JSON: {"is_invoice":true,"matches_reminder":true,"invoice_number":"...","reference_number":"...","amount":123.45,"currency":"PLN","invoice_date":"YYYY-MM-DD","due_date":"YYYY-MM-DD","seller":"...","confidence":"high|medium|low"}','amount = końcowa kwota do zapłaty; due_date = termin płatności; invoice_date = data wystawienia. invoice_number to właściwy numer faktury/dokumentu. Jeżeli dokument ma pola „Numer dokumentu” i „Numer referencyjny”, invoice_number MUSI być wartością z „Numer dokumentu”, a reference_number z „Numer referencyjny”. Nigdy nie podstawiaj numeru referencyjnego, numeru klienta, zamówienia ani polecenia zapłaty jako invoice_number. Nie zgaduj.','Kontekst: '+JSON.stringify(ctx)].join('\n');const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:'Bearer '+OPENAI,'Content-Type':'application/json'},signal:AbortSignal.timeout(60000),body:JSON.stringify({model:'gpt-5.6-luna',reasoning:{effort:'none'},input:[{role:'user',content:[{type:'input_text',text:prompt},{type:'input_file',filename,file_data:'data:application/pdf;base64,'+b64(bytes)}]}],max_output_tokens:320})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(r.status===429?'Brak dostępnego limitu OpenAI API.':'Nie udało się odczytać PDF.');const raw=outputText(j).trim();let p:any;try{p=JSON.parse(raw)}catch{const m=raw.match(/\{[\s\S]*\}/);p=m?JSON.parse(m[0]):null}if(!p)throw new Error('Nie udało się odczytać danych faktury.');const amount=Number(p.amount);return{is_invoice:p.is_invoice===true,matches_reminder:p.matches_reminder===true,invoice_number:clean(p.invoice_number,120)||null,reference_number:clean(p.reference_number,120)||null,amount:Number.isFinite(amount)&&amount>=0?Math.round(amount*100)/100:null,currency:clean(p.currency,8).toUpperCase()||null,invoice_date:dateOk(p.invoice_date),due_date:dateOk(p.due_date),seller:clean(p.seller,160)||null,confidence:['high','medium','low'].includes(p.confidence)?p.confidence:'low'}}

Deno.serve(async req=>{
  if(req.method!=='POST')return json({error:'Method not allowed'},405);
  try{
    const token=req.headers.get('authorization')?.match(/^Bearer (.+)$/i)?.[1];
    if(!token)return json({error:'Zaloguj się ponownie.'},401);
    const auth=await db.auth.getUser(token);if(auth.error||!auth.data.user)return json({error:'Zaloguj się ponownie.'},401);
    const role=await db.from('user_roles').select('role').eq('user_id',auth.data.user.id).maybeSingle();if(role.error||role.data?.role!=='admin')return json({error:'Tylko administrator może sprawdzać faktury.'},403);
    const body=await req.json().catch(()=>({}));const id=clean(body?.reminder_id,80);if(!id)return json({error:'Brak przypomnienia.'},400);
    const q=await db.from('cf_reminders').select('*').eq('id',id).eq('user_id',auth.data.user.id).maybeSingle();if(q.error)throw q.error;const r=q.data;if(!r)return json({error:'Nie znaleziono przypomnienia.'},404);if(!r.mail_invoice_enabled)return json({ok:true,skipped:true});
    const folder=clean(r.mail_folder,128),sender=norm(r.mail_sender),subject=norm(r.mail_subject_contains),fileNeedle=norm(r.mail_attachment_contains);if(!folder||(!sender&&!subject&&!fileNeedle))return json({error:'Uzupełnij folder i filtr faktury.'},422);
    const cr=await db.from('cf_mail_credentials').select('ciphertext').eq('user_id',r.user_id).maybeSingle();if(cr.error)throw cr.error;if(!cr.data?.ciphertext)return json({error:'Brak zapisanego połączenia z pocztą o2.'},422);
    const cfg=await credential(cr.data.ciphertext,r.user_id);
    const client=new ImapFlow({host:'poczta.o2.pl',port:993,secure:true,auth:{user:cfg.email,pass:cfg.password,loginMethod:'LOGIN'},logger:false,disableAutoIdle:true,disableCompression:true,disableBinary:true,connectionTimeout:10000,greetingTimeout:10000,socketTimeout:30000,tls:{rejectUnauthorized:true}});
    client.on('error',()=>{});
    try{
      await client.connect();const folders=await client.list();const exact=folders.find((f:any)=>String(f.path).normalize('NFC')===folder.normalize('NFC'));if(!exact)throw new Error('Wybrany folder poczty nie istnieje.');await client.mailboxOpen(exact.path,{readOnly:true});
      const baseIso=r.mail_anchor_due_at||r.due_at;const targetMonth=localParts(baseIso).date.slice(0,7);const [ty,tm]=targetMonth.split('-').map(Number);const monthStart=new Date(Date.UTC(ty,tm-1,1,0,0,0));const since=new Date(monthStart.getTime()-14*86400000),before=new Date(Date.UTC(tm===12?ty+1:ty,tm===12?0:tm,1,0,0,0));const search:any={since,before};if(sender)search.from=sender;if(subject)search.subject=subject;
      const uids=await client.search(search,{uid:true});if(!uids?.length){await db.from('cf_reminders').update({mail_scan_status:'waiting',mail_last_checked_at:new Date().toISOString(),mail_last_error:null}).eq('id',id);return json({ok:true,found:false,status:'waiting'})}
      const msgs=await client.fetchAll(uids.slice(-80),{uid:true,envelope:true,bodyStructure:true,internalDate:true},{uid:true});const list:any[]=[];
      for(const m of msgs){const received=new Intl.DateTimeFormat('sv-SE',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(m.internalDate));const sub=clean(m.envelope?.subject,300),froms=(m.envelope?.from||[]).map((x:any)=>norm(x.address)).filter(Boolean);if(sender&&!froms.includes(sender))continue;if(subject&&!norm(sub).includes(subject))continue;for(const p of parts(m.bodyStructure)){if(fileNeedle&&!norm(p.filename).includes(fileNeedle))continue;list.push({m,p,sub,froms,time:new Date(m.internalDate).getTime()})}}
      list.sort((a,b)=>b.time-a.time);let best:any=null;
      for(const item of list.slice(0,6)){const bytes=await readPdf(client,item.m.uid,item.p);const a=await analyze(bytes,item.p.filename,{title:r.title,payee:r.payee||'',expected_due:localParts(r.mail_anchor_due_at||r.due_at).date,target_month:targetMonth,email_sender:item.froms.join(', '),email_subject:item.sub,attachment:item.p.filename});if(!a.is_invoice)continue;if(!a.due_date||!a.due_date.startsWith(targetMonth+'-'))continue;best={...a,source:{uid:item.m.uid,subject:item.sub,received:new Intl.DateTimeFormat('sv-SE',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(item.m.internalDate)),attachment:item.p.filename}};if(a.confidence==='high'&&a.matches_reminder)break}
      if(!best){await db.from('cf_reminders').update({mail_scan_status:'waiting',mail_last_checked_at:new Date().toISOString(),mail_last_error:null}).eq('id',id);return json({ok:true,found:false,status:'waiting'})}
      const source={mail_last_checked_at:new Date().toISOString(),mail_last_error:null,mail_source_message_uid:best.source.uid,mail_source_subject:best.source.subject,mail_source_received_at:best.source.received,mail_source_attachment:best.source.attachment,mail_invoice_detected_at:new Date().toISOString(),mail_candidate:best};
      const auto=best.confidence==='high'&&best.matches_reminder&&best.invoice_number&&best.amount!=null&&best.due_date&&best.due_date.startsWith(targetMonth+'-')&&best.currency==='PLN';
      if(!auto){await db.from('cf_reminders').update({...source,mail_scan_status:'needs_review'}).eq('id',id);return json({ok:true,found:true,status:'needs_review',candidate:best})}
      const oldDue=r.due_at,lp=localParts(oldDue),newDue=localIso(best.due_date,lp.time||'09:00');const duration=r.start_at&&r.end_at?Math.max(0,new Date(r.end_at).getTime()-new Date(r.start_at).getTime()):0;const newEnd=duration?new Date(new Date(newDue).getTime()+duration).toISOString():newDue;const newRem=calcRemind(newDue,r.reminder_mode||'at_time',oldDue,r.custom_remind_at);const patch:any={...source,mail_scan_status:'applied',amount:best.amount,invoice_number:best.invoice_number,due_at:newDue,start_at:newDue,end_at:newEnd,remind_at:newRem,push_sent_at:null};if(r.reminder_mode==='custom'&&r.custom_remind_at){const diff=new Date(oldDue).getTime()-new Date(r.custom_remind_at).getTime();patch.custom_remind_at=new Date(new Date(newDue).getTime()-diff).toISOString()}await db.from('cf_reminders').update(patch).eq('id',id);return json({ok:true,found:true,status:'applied',amount:best.amount,invoice_number:best.invoice_number,due_at:newDue})
    }finally{try{client.close()}catch{}}
  }catch(e){return json({error:e instanceof Error?e.message:'Nie udało się sprawdzić poczty.'},422)}
});
