(()=>{
'use strict';
let weekStart=null,rows=[],companies=new Map(),loading=false,draggedId=null,hooked=false;
const pad=n=>String(n).padStart(2,'0');
const ymd=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const add=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
const mon=d=>{const x=new Date(d);x.setHours(12,0,0,0);const k=x.getDay()||7;x.setDate(x.getDate()-k+1);return x};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=m=>{try{if(typeof showToast==='function')showToast(m);else console.info(m)}catch(_){}};
function styles(){if(document.getElementById('cfCal1203Style'))return;const s=document.createElement('style');s.id='cfCal1203Style';s.textContent=`
#cfAdminCalendar,#cfCalendarTile{display:none!important}
#cfCompanyCalendarCard{cursor:pointer}
.cf-cal-modal1203{position:fixed;inset:0;z-index:130000;background:rgba(0,0,0,.46);display:none;align-items:center;justify-content:center;padding:18px}.cf-cal-modal1203.open{display:flex}
.cf-cal-panel1203{width:min(1180px,96vw);max-height:92vh;background:#f7f7f4;border:1px solid rgba(0,0,0,.14);border-radius:18px;box-shadow:0 22px 70px rgba(0,0,0,.28);overflow:hidden;display:flex;flex-direction:column}
.cf-cal-mhead1203{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:16px 18px;background:#fff;border-bottom:1px solid #e2e3df}.cf-cal-mtitle1203{font-size:20px;font-weight:900}.cf-cal-msub1203{font-size:11px;color:#777;margin-top:3px}.cf-cal-close1203{border:0;background:transparent;font-size:25px;cursor:pointer}
.cf-cal-toolbar1203{display:flex;justify-content:space-between;align-items:center;gap:10px;padding:10px 14px;background:#fff;border-bottom:1px solid #e7e7e3}.cf-cal-range1203{font-size:12px;font-weight:800}.cf-cal-nav1203{display:flex;gap:6px}.cf-cal-nav1203 button{border:1px solid #cfd2cf;background:#fff;border-radius:8px;padding:8px 10px;font-weight:800;cursor:pointer}
.cf-cal-body1203{overflow:auto;padding:12px}.cf-cal-week1203{display:grid;grid-template-columns:repeat(7,minmax(135px,1fr));min-width:945px;border:1px solid #e0e2df;border-radius:12px;overflow:hidden;background:#fff}
.cf-cal-day1203{min-height:220px;border-right:1px solid #e7e8e5}.cf-cal-day1203:last-child{border-right:0}.cf-cal-day1203.today{background:#fbfcf7}.cf-cal-day1203.over{outline:2px solid #9ec41a;outline-offset:-2px}
.cf-cal-dayhead1203{padding:9px 10px;border-bottom:1px solid #e7e8e5;display:flex;justify-content:space-between;gap:6px}.cf-cal-dayname1203{font-size:11px;font-weight:900}.cf-cal-date1203{font-size:10px;color:#777}.cf-cal-count1203{font-size:10px;color:#777}
.cf-cal-list1203{padding:7px;display:flex;flex-direction:column;gap:6px;min-height:170px}.cf-cal-item1203{border:1px solid #dcdedb;border-left:4px solid #a6c61b;background:#fff;border-radius:9px;padding:8px;cursor:grab;user-select:none;touch-action:none}.cf-cal-item1203.dragging{opacity:.45}.cf-cal-plate1203{font-size:12px;font-weight:900}.cf-cal-company1203{font-size:9px;color:#666;margin-top:2px}.cf-cal-meta1203{font-size:9px;color:#777;margin-top:3px}
.cf-cal-uns1203{margin-top:10px;background:#fff;border:1px solid #e0e2df;border-radius:12px;padding:10px}.cf-cal-uns-title1203{font-size:11px;font-weight:900;margin-bottom:8px}.cf-cal-uns-list1203{display:flex;gap:7px;overflow:auto;min-height:42px}.cf-cal-uns1203 .cf-cal-item1203{min-width:145px}.cf-cal-empty1203{padding:28px;text-align:center;color:#777;font-size:12px}
@media(max-width:700px){.cf-cal-modal1203{padding:6px}.cf-cal-panel1203{width:100%;max-height:96vh;border-radius:14px}.cf-cal-body1203{padding:8px}.cf-cal-week1203{grid-template-columns:repeat(7,minmax(118px,1fr));min-width:826px}.cf-cal-mtitle1203{font-size:17px}}
`;document.head.appendChild(s)}
function addTile(){const grid=document.getElementById('cfCompanyGrid');if(!grid)return;const adminMarker=grid.querySelector('#cfCompanyUsersCard,#cfCompanyPurchasesCard,#cfCompanyEarningsCard,#cfCompanyRemindersCard,#cfCompanyStatisticsCard,#cfCompanyAddCard');if(!adminMarker)return;document.getElementById('cfCompanyCalendarCard')?.remove();const b=document.createElement('button');b.type='button';b.id='cfCompanyCalendarCard';b.className='cf-company-card cf-company-utility-card';b.innerHTML='<div><strong>Kalendarz</strong><span>Plan pracy i terminy zleceń</span></div>';b.addEventListener('click',openCalendar);const firstUtility=grid.querySelector('#cfCompanyUsersCard,#cfCompanyPurchasesCard,#cfCompanyEarningsCard,#cfCompanyRemindersCard,#cfCompanyStatisticsCard,#cfCompanyAddCard');if(firstUtility)grid.insertBefore(b,firstUtility);else grid.prepend(b)}
function hookRenderer(){if(hooked)return;const fn=window.cfRenderCompanyChooser;if(typeof fn!=='function')return;window.cfRenderCompanyChooser=function(...args){const out=fn.apply(this,args);queueMicrotask(addTile);return out};hooked=true;queueMicrotask(addTile)}
function ensureModal(){let m=document.getElementById('cfCalendarModal1203');if(m)return m;m=document.createElement('div');m.id='cfCalendarModal1203';m.className='cf-cal-modal1203';m.innerHTML=`<div class="cf-cal-panel1203"><div class="cf-cal-mhead1203"><div><div class="cf-cal-mtitle1203">Kalendarz pracy</div><div class="cf-cal-msub1203">Przeciągnij auto na inny dzień, aby zmienić termin tego samego wpisu.</div></div><button class="cf-cal-close1203" type="button">×</button></div><div class="cf-cal-toolbar1203"><div class="cf-cal-range1203"></div><div class="cf-cal-nav1203"><button data-prev>←</button><button data-today>Dziś</button><button data-next>→</button></div></div><div class="cf-cal-body1203"><div class="cf-cal-empty1203">Ładowanie kalendarza…</div></div></div>`;document.body.appendChild(m);m.querySelector('.cf-cal-close1203').onclick=()=>m.classList.remove('open');m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')});m.querySelector('[data-prev]').onclick=()=>{weekStart=add(weekStart||mon(new Date()),-7);render()};m.querySelector('[data-next]').onclick=()=>{weekStart=add(weekStart||mon(new Date()),7);render()};m.querySelector('[data-today]').onclick=()=>{weekStart=mon(new Date());render()};
m.addEventListener('dragstart',e=>{const c=e.target.closest('[data-id]');if(!c)return;draggedId=c.dataset.id;c.classList.add('dragging');try{e.dataTransfer.effectAllowed='move';e.dataTransfer.dropEffect='move';e.dataTransfer.setData('text/plain',draggedId)}catch(_){}});
m.addEventListener('dragend',e=>{e.target.closest('[data-id]')?.classList.remove('dragging');draggedId=null;m.querySelectorAll('.over').forEach(x=>x.classList.remove('over'))});
m.addEventListener('dragover',e=>{const z=e.target.closest('[data-date],[data-uns]');if(!z)return;e.preventDefault();try{e.dataTransfer.dropEffect='move'}catch(_){}m.querySelectorAll('.over').forEach(x=>x.classList.remove('over'));z.classList.add('over')});
m.addEventListener('drop',async e=>{const z=e.target.closest('[data-date],[data-uns]');if(!z)return;e.preventDefault();e.stopPropagation();const id=draggedId||e.dataTransfer?.getData('text/plain');if(!id)return;await moveRecord(id,z.hasAttribute('data-uns')?'':z.dataset.date)});
let pt=null;m.addEventListener('pointerdown',e=>{const c=e.target.closest('[data-id]');if(!c||e.pointerType==='mouse')return;pt={id:c.dataset.id,startX:e.clientX,startY:e.clientY,active:false,pointerId:e.pointerId};c.setPointerCapture?.(e.pointerId)});m.addEventListener('pointermove',e=>{if(!pt)return;const dist=Math.hypot(e.clientX-pt.startX,e.clientY-pt.startY);if(dist<10&&!pt.active)return;pt.active=true;e.preventDefault();m.querySelectorAll('.over').forEach(x=>x.classList.remove('over'));document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-date],[data-uns]')?.classList.add('over')},{passive:false});m.addEventListener('pointerup',async e=>{if(!pt)return;const p=pt;pt=null;if(!p.active)return;const z=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-date],[data-uns]');m.querySelectorAll('.over').forEach(x=>x.classList.remove('over'));if(z)await moveRecord(p.id,z.hasAttribute('data-uns')?'':z.dataset.date)});return m}
const recDate=r=>r.order_due_date||r.schedule_proposed_date||'';
function item(r){const c=companies.get(r.company_id);const cn=c?(c.short_name||c.name):'Firma';const meta=[r.type,r.brand].filter(Boolean).join(' · ');return `<div class="cf-cal-item1203" draggable="true" data-id="${esc(r.id)}"><div class="cf-cal-plate1203">${esc(r.plate)}</div><div class="cf-cal-company1203">${esc(cn)}</div>${meta?`<div class="cf-cal-meta1203">${esc(meta)}</div>`:''}</div>`}
function render(){const m=ensureModal(),body=m.querySelector('.cf-cal-body1203');const start=weekStart||mon(new Date());weekStart=start;const today=ymd(new Date());const cols=[];for(let i=0;i<7;i++){const d=add(start,i),ds=ymd(d),list=rows.filter(r=>recDate(r)===ds);cols.push(`<section class="cf-cal-day1203 ${ds===today?'today':''}" data-date="${ds}"><div class="cf-cal-dayhead1203"><div><div class="cf-cal-dayname1203">${d.toLocaleDateString('pl-PL',{weekday:'short'}).replace('.','').toUpperCase()}</div><div class="cf-cal-date1203">${d.toLocaleDateString('pl-PL',{day:'2-digit',month:'2-digit'})}</div></div><div class="cf-cal-count1203">${list.length}</div></div><div class="cf-cal-list1203">${list.map(item).join('')}</div></section>`)}const uns=rows.filter(r=>!recDate(r));body.innerHTML=`<div class="cf-cal-week1203">${cols.join('')}</div><div class="cf-cal-uns1203" data-uns><div class="cf-cal-uns-title1203">Bez terminu</div><div class="cf-cal-uns-list1203">${uns.length?uns.map(item).join(''):'<span style="font-size:10px;color:#777">Brak wpisów bez terminu</span>'}</div></div>`;m.querySelector('.cf-cal-range1203').textContent=`${start.toLocaleDateString('pl-PL')} – ${add(start,6).toLocaleDateString('pl-PL')}`}
async function load(){if(loading||typeof cfSupabase==='undefined'||!cfSupabase)return;loading=true;try{const [a,b]=await Promise.all([cfSupabase.from('companies').select('id,name,short_name').eq('active',true),cfSupabase.from('wash_records').select('id,company_id,plate,type,brand,order_due_date,schedule_proposed_date,wash_date,schedule_status').is('wash_date',null).order('created_at',{ascending:false})]);if(a.error)throw a.error;if(b.error)throw b.error;companies=new Map((a.data||[]).map(x=>[x.id,x]));rows=(b.data||[]).filter(x=>x.company_id);render()}catch(e){console.error('calendar v1203',e);ensureModal().querySelector('.cf-cal-body1203').innerHTML='<div class="cf-cal-empty1203">Nie udało się pobrać kalendarza.</div>'}finally{loading=false}}
async function moveRecord(id,date){const r=rows.find(x=>x.id===id);if(!r||typeof cfSupabase==='undefined')return;const old=recDate(r);if(old===date)return;const snapshot={order_due_date:r.order_due_date,schedule_proposed_date:r.schedule_proposed_date,schedule_status:r.schedule_status};try{const payload=date?{order_due_date:date,schedule_proposed_date:null,schedule_status:'accepted'}:{order_due_date:null,schedule_proposed_date:null,schedule_status:null};const {data,error}=await cfSupabase.from('wash_records').update(payload).eq('id',id).select('id,order_due_date,schedule_proposed_date,schedule_status').maybeSingle();if(error)throw error;if(!data)throw new Error('Brak potwierdzenia zapisu');r.order_due_date=data.order_due_date||null;r.schedule_proposed_date=data.schedule_proposed_date||null;r.schedule_status=data.schedule_status||null;render();toast(date?`Termin ${r.plate}: ${date}`:`${r.plate}: usunięto termin`)}catch(e){r.order_due_date=snapshot.order_due_date;r.schedule_proposed_date=snapshot.schedule_proposed_date;r.schedule_status=snapshot.schedule_status;render();console.error('calendar move',e);toast('Nie udało się zmienić terminu w bazie') }}
async function openCalendar(){const m=ensureModal();m.classList.add('open');await load()}
function boot(){styles();ensureModal();hookRenderer();addTile();[100,300,700,1500,3000].forEach(ms=>setTimeout(()=>{hookRenderer();addTile()},ms));document.addEventListener('visibilitychange',()=>{if(!document.hidden){hookRenderer();addTile()}});window.addEventListener('focus',()=>{hookRenderer();addTile()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();