(function(root){
'use strict';
let active=null;
function close(){const dialog=active;active=null;if(dialog){if(dialog.open)dialog.close();dialog.remove();}}
function amount(invoice){const raw=invoice.gross;if(raw===null||raw===undefined||String(raw).trim()==='')return 'Brak kwoty';const number=Number(raw);return Number.isFinite(number)?new Intl.NumberFormat('pl-PL',{minimumFractionDigits:2,maximumFractionDigits:2}).format(number)+' '+(invoice.currency||''):'Brak kwoty';}
function totals(invoices){
 const sums=new Map();let missing=0;
 for(const invoice of invoices){const match=String(invoice.gross??'').trim().match(/^([+-]?)(\d+)(?:\.(\d{1,2}))?$/),currency=String(invoice.currency||'').trim().toUpperCase();if(!match||! /^[A-Z]{3}$/.test(currency)){missing++;continue;}const cents=(match[1]==='-'?-1n:1n)*(BigInt(match[2])*100n+BigInt((match[3]||'').padEnd(2,'0')));sums.set(currency,(sums.get(currency)||0n)+cents);}
 const amounts=[...sums].sort(([a],[b])=>a.localeCompare(b)).map(([currency,cents])=>{const absolute=cents<0n?-cents:cents;return (cents<0n?'-':'')+new Intl.NumberFormat('pl-PL',{maximumFractionDigits:0}).format(absolute/100n)+','+String(absolute%100n).padStart(2,'0')+' '+currency;});
 return {amounts,missing};
}
function date(value){const text=String(value||'');return /^\d{4}-\d{2}-\d{2}$/.test(text)?text.slice(8)+'.'+text.slice(5,7)+'.'+text.slice(0,4):text||'Brak daty';}
function open(results,month){
 close();
 const dialog=document.createElement('dialog');dialog.id='cfKsefPreviewDialog';dialog.setAttribute('aria-labelledby','cfKsefPreviewTitle');active=dialog;
 const add=(parent,tag,text,cls)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;parent.appendChild(node);return node;};
 add(dialog,'style',`#cfKsefPreviewDialog{position:fixed;inset:0;margin:auto;height:fit-content;width:min(1040px,calc(100vw - 24px));max-height:calc(100dvh - 24px - env(safe-area-inset-top) - env(safe-area-inset-bottom));padding:0;border:1px solid #dde3d7;border-radius:14px;background:#fff;color:#222820;font:14px/1.45 system-ui,-apple-system,sans-serif;overflow:hidden}#cfKsefPreviewDialog::backdrop{background:rgba(20,24,20,.55)}#cfKsefPreviewDialog *{box-sizing:border-box}#cfKsefPreviewDialog .kp-sheet{display:flex;flex-direction:column;max-height:inherit}#cfKsefPreviewDialog .kp-head{display:flex;align-items:center;justify-content:space-between;gap:14px;padding:16px 18px;border-bottom:1px solid #e3e7dd;flex-shrink:0;background:#fff}#cfKsefPreviewDialog h2{margin:0;font-size:20px}#cfKsefPreviewDialog h3{margin:0 0 10px;font-size:17px}#cfKsefPreviewDialog .kp-head p{margin:4px 0 0;color:#67705e}#cfKsefPreviewDialog button{padding:10px 14px;border:1px solid #cbd5ad;border-radius:8px;color:#526115;background:#f6fbe9;font:600 14px system-ui;cursor:pointer;white-space:nowrap;min-height:44px}#cfKsefPreviewDialog .kp-body{overflow:auto;min-height:0;padding:18px;-webkit-overflow-scrolling:touch;overscroll-behavior:contain}#cfKsefPreviewDialog section+section{margin-top:26px}#cfKsefPreviewDialog .kp-table{overflow-x:auto;border:1px solid #e0e5dc;border-radius:8px}#cfKsefPreviewDialog table{border-collapse:collapse;width:100%;min-width:550px;table-layout:fixed}#cfKsefPreviewDialog th,#cfKsefPreviewDialog td{padding:10px 12px;text-align:left;border-bottom:1px solid #e4e8df;vertical-align:top;overflow-wrap:anywhere}#cfKsefPreviewDialog th{background:#f2f5ee;font-weight:650}#cfKsefPreviewDialog th:nth-child(1){width:25%}#cfKsefPreviewDialog th:nth-child(2){width:35%}#cfKsefPreviewDialog th:nth-child(3){width:23%}#cfKsefPreviewDialog th:nth-child(4){width:17%}#cfKsefPreviewDialog tbody tr:last-child td{border-bottom:0}#cfKsefPreviewDialog tfoot td{background:#f2f5ee;font-weight:700;border-top:2px solid #cfd8c4}#cfKsefPreviewDialog small{display:block;margin-top:3px;color:#687260}#cfKsefPreviewDialog .kp-amount{font-variant-numeric:tabular-nums}@media(max-width:600px){#cfKsefPreviewDialog .kp-head,#cfKsefPreviewDialog .kp-body{padding:12px}#cfKsefPreviewDialog h2{font-size:18px}#cfKsefPreviewDialog table{min-width:0;font-size:12px}#cfKsefPreviewDialog th,#cfKsefPreviewDialog td{padding:9px 6px}#cfKsefPreviewDialog th:nth-child(1){width:22%}#cfKsefPreviewDialog th:nth-child(2){width:30%}#cfKsefPreviewDialog th:nth-child(3){width:26%}#cfKsefPreviewDialog th:nth-child(4){width:22%}#cfKsefPreviewDialog th{font-size:11px;overflow-wrap:normal}#cfKsefPreviewDialog .kp-date{font-size:11px;white-space:nowrap}}`);
 const sheet=add(dialog,'div',undefined,'kp-sheet'),header=add(sheet,'header',undefined,'kp-head'),titleBox=add(header,'div');add(titleBox,'h2','Podgląd faktur KSeF').id='cfKsefPreviewTitle';add(titleBox,'p','Miesiąc: '+month+' · Kwoty brutto');const button=add(header,'button','Zamknij');button.type='button';button.addEventListener('click',close);
 const body=add(sheet,'div',undefined,'kp-body');
 for(const [kind,title,partyLabel] of [['purchases','Faktury zakupowe','Sprzedawca'],['sales','Faktury sprzedażowe','Nabywca']]){
  const invoices=[...(results[kind]?.invoices||[])].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))||String(a.number||'').localeCompare(String(b.number||''),'pl'));
  const section=add(body,'section');add(section,'h3',title+' ('+invoices.length+')');
  if(!invoices.length){add(section,'p','Brak faktur w wybranym miesiącu.');continue;}
  const table=add(add(section,'div',undefined,'kp-table'),'table');table.setAttribute('aria-label',title);const head=add(add(table,'thead'),'tr');for(const label of ['Numer faktury',partyLabel,'Kwota brutto','Data']){const th=add(head,'th',label);th.scope='col';if(label==='Data')th.title='Data wystawienia';}
  const rows=add(table,'tbody');for(const invoice of invoices){const row=add(rows,'tr');add(row,'td',invoice.number||invoice.nrKSeF||'Brak numeru');const party=add(row,'td',kind==='purchases'?(invoice.seller||'Sprzedawca niewskazany'):(invoice.buyer||'Nabywca niewskazany'));const nip=kind==='purchases'?invoice.nip:invoice.buyerNip;if(nip)add(party,'small','NIP: '+nip);add(row,'td',amount(invoice),'kp-amount');add(row,'td',date(invoice.date),'kp-date');}
  const summary=totals(invoices),footer=add(table,'tfoot'),totalRow=add(footer,'tr'),totalLabel=add(totalRow,'td',kind==='purchases'?'Łączne koszty brutto':'Łączne przychody brutto');totalLabel.colSpan=2;
  const totalAmount=add(totalRow,'td',undefined,'kp-amount');if(!summary.amounts.length)totalAmount.textContent='Brak danych';else for(const value of summary.amounts)add(totalAmount,'div',value);add(totalRow,'td','—');
  if(summary.missing){const note=add(add(footer,'tr'),'td','Podsumowanie częściowe: '+summary.missing+' faktur ma niepełną kwotę lub walutę.');note.colSpan=4;}
 }
 dialog.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();event.stopPropagation();close();}});
 dialog.addEventListener('cancel',event=>{event.preventDefault();close();});
 dialog.addEventListener('click',event=>{if(event.target!==dialog)return;const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)close();});
 document.body.appendChild(dialog);dialog.showModal();button.focus({preventScroll:true});return dialog;
}
root.CFKsefPreview={open,close,totals};
})(typeof window==='object'?window:globalThis);
