import {keyFor,newSalt,seal,open,checkEnvelope} from './vault.js?v=100';
const P=window.Payments,$=id=>document.getElementById(id),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=(n,c='PLN')=>new Intl.NumberFormat('pl-PL',{style:'currency',currency:c}).format(n/100),today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Warsaw'}).format(new Date()),id=()=>crypto.randomUUID();
let db,user,state,key,salt,envelope,revision=0,busy=false,generation=0,lockTimer,pdfLib,passwordPromptCancel=null,importInFlight=false,importMode='history';
const empty=()=>({version:1,rules:[],transactions:[],imports:[]});
const monthNames=['Sty','Lut','Mar','Kwi','Maj','Cze','Lip','Sie','Wrz','Paź','Lis','Gru'];
function validate(s){if(s?.version!==1||!Array.isArray(s.rules)||!Array.isArray(s.transactions)||!Array.isArray(s.imports))throw Error('Nieprawidłowe dane kopii.');for(const t of s.transactions)if(!P.date(t.date)||!Number.isSafeInteger(t.amount)||t.amount<=0||!['PLN','EUR','USD','GBP'].includes(t.currency))throw Error('Kopia zawiera nieprawidłowe przelewy.');return s;}
function notice(text,error=false){$('message').hidden=false;$('message').className='notice'+(error?' error':'');$('message').textContent=text;}
function modal(title,body,foot=''){if(!key||!state)return; $('modalTitle').textContent=title;$('modalBody').innerHTML=body;$('modalFoot').innerHTML=foot;if(!$('modal').open)$('modal').showModal();}
function close(){if(busy)return;passwordPromptCancel?.();$('modal').close();$('modalBody').replaceChildren();$('modalFoot').replaceChildren();}
function lock(){generation++;passwordPromptCancel?.();state=null;key=null;salt=null;envelope=null;clearTimeout(lockTimer);$('main').hidden=true;$('gate').hidden=false;$('payments').replaceChildren();$('stats').replaceChildren();$('monthlyDue').replaceChildren();$('message').hidden=true;$('pin').value='';$('repeatPin').value='';$('modal').close();$('modalBody').replaceChildren();$('modalFoot').replaceChildren();$('pdfFile').value='';$('gateInfo').textContent='Wpisz PIN lub hasło, aby odszyfrować płatności.';}
function activity(){if(key){clearTimeout(lockTimer);lockTimer=setTimeout(lock,10*60*1000);}}
async function loadEnvelope(){const {data,error}=await db.from('cf_payment_vaults').select('envelope,revision').eq('user_id',user.id).maybeSingle();if(error)throw Error('Nie można pobrać płatności: '+error.message);revision=data?.revision||0;envelope=data?.envelope||null;return envelope;}
async function persist(next,newKey=key,newSaltValue=salt){if(!key||busy)throw Error('Operacja jest już w toku lub narzędzie jest zablokowane.');busy=true;const epoch=generation;try{const encrypted=await seal(validate(next),newKey,newSaltValue);if(epoch!==generation)throw Error('Narzędzie zostało zablokowane. Otwórz je ponownie.');const {data,error}=await db.rpc('cf_save_payment_vault',{p_envelope:encrypted,p_revision:revision});if(error)throw Error(error.message.includes('PAYMENT_CONFLICT')?'Dane zmieniły się na innym urządzeniu. Zablokuj i otwórz narzędzie ponownie przed kolejnym zapisem.':error.message);if(epoch!==generation)return;revision=data;envelope=encrypted;state=next;key=newKey;salt=newSaltValue;activity();render();notice('Zapisano.');}finally{busy=false;}}
async function action(fn){try{await fn();}catch(e){notice(e.message||'Nie udało się wykonać operacji.',true);if($('modal').open){let error=$('modalError');if(!error){error=document.createElement('p');error.id='modalError';error.className='error';$('modalFoot').prepend(error);}error.textContent=e.message;}}}
function render(){if(!state)return;const currentYear=Number(today().slice(0,4)),selected=$('year').value||String(currentYear);const years=new Set([currentYear,Number(selected),...state.transactions.map(t=>Number(t.date.slice(0,4))),...state.rules.map(r=>Number(r.start.slice(0,4)))]);$('year').innerHTML=[...years].sort((a,b)=>b-a).map(y=>`<option ${String(y)===selected?'selected':''}>${y}</option>`).join('');let paid=0,missing=0,unknown=0;
  const currentMonth=today().slice(0,7),schedule=P.schedule(state.rules,currentMonth),monthLabel=new Intl.DateTimeFormat('pl-PL',{month:'long',year:'numeric',timeZone:'Europe/Warsaw'}).format(new Date(today()+'T12:00:00Z'));
  $('monthlyDue').hidden=!state.rules.length;$('monthlyDue').innerHTML=`<h3>Płatności w tym miesiącu · ${escape(monthLabel)}</h3><div class="due-items">${schedule.map(({rule,due})=>`<button class="due-item" type="button" data-jump="${escape(rule.id)}"><strong>${escape(rule.name)}</strong><span>Termin: <time datetime="${due}">${due.split('-').reverse().join('.')}</time></span></button>`).join('')||'<p class="muted">Brak pozycji objętych kontrolą w tym miesiącu.</p>'}</div>`;
  $('payments').innerHTML=state.rules.length?state.rules.map(rule=>{const expenses=state.transactions.filter(t=>t.currency===rule.currency&&P.allocation(state,t)?.rule.id===rule.id),total=expenses.reduce((sum,t)=>sum+t.amount,0),yearTotal=expenses.filter(t=>t.date.startsWith(selected+'-')).reduce((sum,t)=>sum+t.amount,0);const months=monthNames.map((name,i)=>{const month=selected+'-'+String(i+1).padStart(2,'0'),s=P.status(state,rule,month,today());if(s.kind==='paid')paid++;if(s.kind==='missing')missing++;if(s.kind==='unknown')unknown++;return `<button class="month ${s.kind}" data-rule="${escape(rule.id)}" data-month="${month}"><b>${name}</b><span>${s.label}</span>${s.transactions.length?`<strong>${money(s.total,rule.currency)}</strong><small>${s.transactions.length} przelew${s.transactions.length===1?'':'y'}</small>`:`<small>${s.due?'Termin: '+s.due:''}</small>`}</button>`;}).join('');return `<article class="card payment-card" id="payment-${escape(rule.id)}" tabindex="-1"><div class="payment-head"><div><h3>${escape(rule.name)}</h3><small>${escape(rule.recipient)} · ${rule.expected==null?'Kwota zmienna':money(rule.expected,rule.currency)} · do ${rule.day}. dnia${rule.offset===-1?' następnego miesiąca':rule.offset===1?' poprzedniego miesiąca':''}</small></div><button data-edit="${escape(rule.id)}">Edytuj</button></div><div class="payment-totals"><div><small>Wydano w ${selected}</small><strong>${money(yearTotal,rule.currency)}</strong></div><div><small>Wydano łącznie · cała historia</small><strong>${money(total,rule.currency)}</strong></div></div><small>Według dat płatności z wczytanych wyciągów.</small><div class="months">${months}</div></article>`;}).join(''):'<div class="card empty"><h2>Zacznij od wyciągu</h2><p>Wczytaj historię przelewów z mBanku i zaznacz płatności, które chcesz kontrolować.</p><button class="primary" data-start>Zaczytaj z wyciągu</button></div>';
  $('stats').innerHTML=`<div class="card"><small>Potwierdzone miesiące</small><strong>${paid}</strong></div><div class="card"><small>Brak płatności</small><strong>${missing}</strong></div><div class="card"><small>Brak potwierdzenia</small><strong>${unknown}</strong></div>`;const visible=state.transactions.filter(t=>P.tracked([t],state.rules).length||state.rules.some(r=>r.id===t.assignment)),unmatched=visible.filter(t=>!t.assignment&&!P.allocation(state,t)).length;
  $('coverage').textContent=`${state.imports.length} zaimportowanych wyciągów · ${visible.length} przelewów z listy · ${unmatched} bez jednoznacznego dopasowania. Brak płatności wskazujemy tylko dla pełnych miesięcy objętych wyciągami. Kliknij miesiąc, aby zobaczyć szczegóły.`;
  $('monthlyDue').querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>jumpToPayment(b.dataset.jump));
  $('payments').querySelectorAll('[data-rule]').forEach(b=>b.onclick=()=>showMonth(b.dataset.rule,b.dataset.month));$('payments').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editList(b.dataset.edit));$('payments').querySelector('[data-start]')?.addEventListener('click',()=>choosePdf());
}
function jumpToPayment(ruleId){const card=document.getElementById('payment-'+ruleId);if(!card)return;card.focus({preventScroll:true});card.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});}
function ruleHtml(r){return `<div class="rule" data-id="${escape(r.id)}"><div class="form-grid"><label>Nazwa<input data-field="name" value="${escape(r.name)}" required></label><label>Oczekiwana kwota (puste = zmienna)<input data-field="expected" inputmode="decimal" value="${r.expected==null?'':(r.expected/100).toFixed(2)}"></label><label>Waluta<select data-field="currency">${['PLN','EUR','USD','GBP'].map(c=>`<option ${c===r.currency?'selected':''}>${c}</option>`).join('')}</select></label><label>Termin: dzień miesiąca<input data-field="day" type="number" min="1" max="31" value="${r.day}"></label><label>Przelew dotyczy<select data-field="offset"><option value="0" ${r.offset===0?'selected':''}>Miesiąca przelewu</option><option value="-1" ${r.offset===-1?'selected':''}>Poprzedniego miesiąca</option><option value="1" ${r.offset===1?'selected':''}>Następnego miesiąca</option></select></label><label>Kontroluj od miesiąca<input data-field="start" type="month" value="${escape(r.start)}"></label><label>Kontroluj do (opcjonalnie)<input data-field="end" type="month" value="${escape(r.end||'')}"></label><label>Odbiorca do rozpoznawania<input data-field="recipient" value="${escape(r.recipient)}"></label><label>Rachunek odbiorcy (26 cyfr)<input data-field="account" value="${escape(r.account)}" inputmode="numeric"></label><label>Fragment tytułu (opcjonalnie)<input data-field="phrase" value="${escape(r.phrase||'')}" placeholder="np. alimenty"></label></div><div class="actions"><button class="danger" data-remove>Usuń z kontroli</button></div><small>Rozpoznawanie: rachunek, a bez rachunku dokładna nazwa odbiorcy; dodatkowo fragment tytułu, jeżeli podany.</small></div>`;}
function readRules(){return [...$('modalBody').querySelectorAll('.rule')].map(el=>{const v=f=>el.querySelector(`[data-field="${f}"]`).value.trim();const expected=v('expected')?P.cents(v('expected')):null,day=Number(v('day')),account=v('account').replace(/\s/g,'');if(!v('name')||!v('recipient')&&!account||expected!=null&&expected<0||v('expected')&&expected==null||!Number.isInteger(day)||day<1||day>31||!/^\d{4}-\d{2}$/.test(v('start'))||account&&!/^\d{26}$/.test(account)||v('end')&&v('end')<v('start'))throw Error('Sprawdź nazwę, odbiorcę lub rachunek, kwotę, termin i miesiące każdej pozycji.');return {...state.rules.find(r=>r.id===el.dataset.id),id:el.dataset.id,aliases:state.rules.find(r=>r.id===el.dataset.id&&r.recipient===v('recipient'))?.aliases||[],name:v('name'),expected,currency:v('currency'),day,offset:Number(v('offset')),start:v('start'),end:v('end')||null,recipient:v('recipient'),account,accounts:state.rules.find(r=>r.id===el.dataset.id&&r.account===account)?.accounts||[],phrase:v('phrase')};});}
function bindRuleActions(){ $('modalBody').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>b.closest('.rule').remove());}
function editList(focus){modal('Edytuj listę',`<p>Zmiana nazwy zachowuje historię. Usunięcie pozycji pozostawia przelewy w historii. Aby dodać z wyciągu, najpierw zapisz edytowaną listę.</p><div id="rules">${state.rules.map(ruleHtml).join('')}</div><button id="addRule">Dodaj ręcznie</button>`,`<div class="toolbar"><button class="primary" id="saveRules">Zapisz listę</button><button id="importFromList">Zapisz i zaczytaj z wyciągu</button></div>`);bindRuleActions();$('addRule').onclick=()=>{$('rules').insertAdjacentHTML('beforeend',ruleHtml({id:id(),name:'',recipient:'',account:'',expected:null,currency:'PLN',day:10,offset:0,start:today().slice(0,7)}));bindRuleActions();};const save=async()=>{const next=structuredClone(state);next.rules=readRules();await persist(next);close();};$('saveRules').onclick=()=>action(save);$('importFromList').onclick=()=>action(async()=>{await save();showContractorUpload();});if(focus)$('modalBody').querySelector(`[data-id="${focus}"]`)?.scrollIntoView({block:'center'});}
function showMergeList(){
  modal('Scal pozycje',`<p>Zaznacz co najmniej dwie pozycje i wybierz, która nazwa ma pozostać. Zachowamy ustawienia tej pozycji, wszystkie warianty odbiorców oraz historię płatności. Kontrola obejmie łączny zakres zaznaczonych pozycji.</p><div id="mergeRows">${state.rules.map(r=>`<label class="contractor-row"><input type="checkbox" data-merge-rule value="${escape(r.id)}"><div><strong>${escape(r.name)}</strong><small style="display:block">${escape(r.currency)}</small></div></label>`).join('')}</div>`,`<label>Nazwa i ustawienia, które pozostaną<select id="mergeTarget" disabled><option value="">Najpierw zaznacz pozycje</option></select></label><p id="mergeCount" class="muted">Zaznaczono: 0</p><button id="mergeSelected" class="primary" disabled>Scal</button>`);
  const selected=()=>[...$('mergeRows').querySelectorAll('[data-merge-rule]:checked')].map(c=>c.value);
  const refresh=()=>{const ids=selected(),previous=$('mergeTarget').value;$('mergeTarget').innerHTML=ids.length?state.rules.filter(r=>ids.includes(r.id)).map(r=>`<option value="${escape(r.id)}">${escape(r.name)}</option>`).join(''):'<option value="">Najpierw zaznacz pozycje</option>';if(ids.includes(previous))$('mergeTarget').value=previous;$('mergeTarget').disabled=ids.length<2;$('mergeSelected').disabled=ids.length<2;$('mergeCount').textContent='Zaznaczono: '+ids.length;};
  $('mergeRows').querySelectorAll('[data-merge-rule]').forEach(c=>c.onchange=refresh);
  $('mergeSelected').onclick=()=>action(async()=>{const ids=selected(),target=$('mergeTarget').value;if(ids.length<2||!ids.includes(target))throw Error('Zaznacz co najmniej dwie pozycje i wybierz nazwę, która ma pozostać.');const next=structuredClone(state);P.mergeRules(next,target,ids);const name=next.rules.find(r=>r.id===target).name;await persist(next);close();notice(`Scalono ${ids.length} pozycji w „${name}”. Historia płatności została zachowana.`);});
}
function showMonth(ruleId,month){const rule=state.rules.find(r=>r.id===ruleId),s=P.status(state,rule,month,today());modal(rule.name+' · '+month,`<div class="notice ${s.kind}"><strong>${s.label}</strong><p>Zapłacono: ${money(s.total,rule.currency)}${rule.expected==null?'':' · oczekiwano: '+money(rule.expected,rule.currency)}${s.difference==null?'':' · różnica: '+money(s.difference,rule.currency)}</p></div>${s.transactions.map(t=>`<div class="rule"><b>${t.date} · ${money(t.amount,t.currency)}</b><p>${escape(t.recipient)}</p><p>${escape(t.title)}</p></div>`).join('')||'<p>Nie znaleziono przypisanego przelewu. Możesz sprawdzić i przypisać go w historii.</p>'}`,`<button id="goHistory">Otwórz historię przelewów</button>`);$('goHistory').onclick=showHistory;}
function showHistory(){modal('Historia przelewów',`<div class="inline"><label>Wyszukaj<input id="historySearch" type="search" placeholder="Odbiorca, tytuł, data"></label><label>Widok<select id="historyFilter"><option value="all">Wszystkie</option><option value="unmatched">Bez dopasowania</option></select></label></div><div id="historyRows"></div>`,'<p>Przypisanie i miesiąc zapisują się od razu po zmianie. „Automatycznie” przywraca rozpoznawanie według listy.</p>');const renderRows=()=>{const q=P.normalize($('historySearch').value),filter=$('historyFilter').value;const tx=state.transactions.filter(t=>(P.tracked([t],state.rules).length||state.rules.some(r=>r.id===t.assignment))&&(filter!=='unmatched'||!P.allocation(state,t)&&t.assignment!=='__ignore__')&&P.normalize(t.recipient+' '+t.title+' '+t.date).includes(q)).sort((a,b)=>b.date.localeCompare(a.date));$('historyRows').innerHTML=tx.map(t=>{const a=P.allocation(state,t);return `<div class="history-row" data-tx="${t.id}"><div><b>${t.date} · ${money(t.amount,t.currency)}</b><p>${escape(t.recipient)}</p><small>${escape(t.sourceName||'')}</small></div><div><p>${escape(t.title)}</p><small>${escape(t.account)}</small><details><summary>Tekst z PDF</summary><p class="source">${escape(t.raw||'')}</p></details></div><div><label>Pozycja<select data-assign><option value="">Automatycznie${a&&!t.assignment?' · '+escape(a.rule.name):''}</option><option value="__ignore__" ${t.assignment==='__ignore__'?'selected':''}>Nie kontroluj</option>${state.rules.filter(r=>r.currency===t.currency).map(r=>`<option value="${r.id}" ${t.assignment===r.id?'selected':''}>${escape(r.name)}</option>`).join('')}</select></label><label>Dotyczy miesiąca<input data-month type="month" value="${escape(t.month||a?.month||'')}"></label></div></div>`;}).join('')||'<p class="empty">Brak przelewów w tym widoku.</p>'; $('historyRows').querySelectorAll('[data-tx]').forEach(row=>{for(const el of row.querySelectorAll('select,input'))el.onchange=()=>action(async()=>{const next=structuredClone(state),target=next.transactions.find(t=>t.id===row.dataset.tx);target.assignment=row.querySelector('[data-assign]').value||null;const m=row.querySelector('[data-month]').value;target.month=m||null;try{await persist(next);renderRows();}catch(e){renderRows();throw e;}});});};$('historySearch').oninput=renderRows;$('historyFilter').onchange=renderRows;renderRows();}
function choosePdf(mode='history'){if(busy||importInFlight)return;importMode=mode==='contractors'||!state.rules.length?'contractors':'history';$('pdfFile').click();}
function showContractorUpload(){
  modal('Dodaj pozycje z wyciągu',`<p>Lista została zapisana. Wybierz PDF, aby wskazać nowych kontrahentów do kontroli.</p><label>Wyciąg z mBanku<input id="contractorPdf" type="file" accept="application/pdf,.pdf" multiple></label>`);
  $('contractorPdf').onchange=()=>{const files=[...$('contractorPdf').files];$('contractorPdf').value='';handlePdfFiles(files,'contractors');};
}
function handlePdfFiles(files,mode=importMode){
  if(!files.length||importInFlight||busy)return;importMode=mode;
  return action(async()=>{importInFlight=true;const controls=['editList','mergeList','import','history','settings'].map($);controls.forEach(b=>b.disabled=true);try{await preview(files);}finally{importInFlight=false;controls.forEach(b=>b.disabled=false);}});
}
function requestPdfPassword(name,incorrect=false){
  if(!key||!state)return Promise.reject(Error('Narzędzie jest zablokowane.'));
  return new Promise((resolve,reject)=>{
    modal('Hasło do wyciągu',`<p>${escape(name)}</p><p>${incorrect?'Poprzednie hasło było nieprawidłowe. Spróbuj ponownie.':'Ten PDF jest zabezpieczony. Podaj hasło otrzymane z mBanku.'}</p><form id="pdfPasswordForm"><label>Hasło do pliku PDF<input id="pdfPassword" type="password" autocomplete="off" required spellcheck="false"></label></form><p class="muted">Hasło służy tylko do odczytu na tym urządzeniu. Nie zapisujemy go.</p>`,`<div class="toolbar"><button type="submit" form="pdfPasswordForm" class="primary">Odczytaj PDF</button><button type="button" id="cancelPdfPassword">Anuluj odczyt</button></div>`);
    let done=false;
    const finish=(value,cancel=false)=>{if(done)return;done=true;passwordPromptCancel=null;$('pdfPassword').value='';$('modal').close();$('modalBody').replaceChildren();$('modalFoot').replaceChildren();cancel?reject(Error('Anulowano odczyt wyciągu.')):resolve(value);};
    passwordPromptCancel=()=>finish(null,true);
    $('cancelPdfPassword').onclick=passwordPromptCancel;
    $('pdfPasswordForm').onsubmit=e=>{e.preventDefault();const value=$('pdfPassword').value;if(value)finish(value);};
    $('pdfPassword').focus();
  });
}
async function readPdf(file){
  if(file.size>25*1024*1024)throw Error('PDF jest za duży. Limit: 25 MB.');
  pdfLib||=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.min.mjs');
  pdfLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.worker.min.mjs';
  const task=pdfLib.getDocument({data:new Uint8Array(await file.arrayBuffer()),isEvalSupported:false});
  let doc,abort;const cancelled=new Promise((_,reject)=>{abort=reject;});
  task.onPassword=(updatePassword,reason)=>{requestPdfPassword(file.name,reason===pdfLib.PasswordResponses.INCORRECT_PASSWORD).then(updatePassword).catch(error=>{abort(error);task.destroy().catch(()=>{});});};
  try{
    doc=await Promise.race([task.promise,cancelled]);
    if(doc.numPages>300)throw Error('PDF ma za dużo stron (limit 300).');
    const pages=[];for(let p=1;p<=doc.numPages;p++){notice(`Odczytuję ${file.name}: strona ${p}/${doc.numPages}…`);const page=await doc.getPage(p);pages.push(P.rowsFromItems((await page.getTextContent()).items));}
    return P.parsePages(pages);
  }finally{if(doc)await doc.destroy();else await task.destroy().catch(()=>{});}
}
function importOptions(batches){return batches.map((b,i)=>`<section class="import-source" data-batch="${i}"><b>${escape(b.name)}</b><label class="checkline"><input type="checkbox" data-complete ${b.warnings.length||!b.range?'disabled':''}>Wyciąg zawiera wszystkie operacje z podanego okresu</label>${b.warnings.length?'<p class="error">Nie odczytano wszystkich kwot. Ten plik nie potwierdzi kompletności miesiąca.</p>':''}</section>`).join('');}
function appendImport(next,batches,transactions){
  for(const section of $('modalBody').querySelectorAll('[data-batch]')){const b=batches[Number(section.dataset.batch)],complete=section.querySelector('[data-complete]').checked,from=b.range?.from||null,to=b.range?.to||null;
    if(complete&&(b.warnings.length||!from||!to||b.transactions.some(t=>t.date<from||t.date>to)))throw Error('Nie można potwierdzić pełnego zakresu wyciągu z błędami odczytu.');
    const previous=next.imports.find(i=>i.hash===b.hash),item={id:previous?.id||id(),hash:b.hash,name:b.name,from,to,complete:complete||!!previous?.complete&&!b.warnings.length,unreadCount:b.warnings.length,importedAt:new Date().toISOString()};
    if(previous)Object.assign(previous,item);else next.imports.push(item);
  }
  next.transactions=P.mergeTransactions(next.transactions,P.tracked(transactions,next.rules));
}
async function preview(files){
  const epoch=generation,batches=[],mode=importMode;notice('Odczytuję PDF…');
  for(const file of files){const parsed=await readPdf(file);if(epoch!==generation)return;const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer()))].map(x=>x.toString(16).padStart(2,'0')).join('');if(batches.some(b=>b.hash===hash))continue;batches.push({hash,name:file.name,...parsed});}
  if(!batches.length)return;
  const transactions=batches.flatMap(b=>b.transactions.map(t=>({...t,id:id(),sourceName:b.name,sourceHash:b.hash}))),unread=batches.flatMap(b=>(b.unread||[]).map(t=>({...t,sourceName:b.name})));
  if(mode==='contractors'){
    const candidates=P.candidates([...transactions,...unread]).filter(t=>!state.rules.some(r=>P.matches(r,t)));
    modal('Wybierz kontrahentów',`<p>Zaznacz kontrahentów, których chcesz kontrolować. Każdy odbiorca występuje na liście tylko raz.</p><label>Wyszukaj kontrahenta<input id="importSearch" type="search" placeholder="Nazwa kontrahenta"></label><p id="importSelected" class="muted">Zaznaczono: 0</p><div id="importRows" class="import-list">${candidates.map((t,i)=>`<label class="contractor-row" data-search="${escape(P.normalize(t.recipient))}"><input type="checkbox" data-track value="${i}"><div><strong>${escape(t.recipient)}</strong>${P.similarRules(t,state.rules).length?`<small style="display:block">Podobna pozycja już istnieje: ${escape(P.similarRules(t,state.rules)[0].name)}. Możesz ją scalić w następnym kroku.</small>`:''}</div></label>`).join('')||'<p>Brak nowych kontrahentów. Istniejące pozycje możesz zmienić w „Edytuj listę”.</p>'}</div>`,`<button id="saveImport" class="primary">Dalej — ustaw wybrane pozycje</button>`);
    $('importSearch').oninput=()=>{const q=P.normalize($('importSearch').value);$('importRows').querySelectorAll('[data-search]').forEach(row=>row.hidden=!row.dataset.search.includes(q));};
    $('importRows').querySelectorAll('[data-track]').forEach(c=>c.onchange=()=>{$('importSelected').textContent='Zaznaczono: '+$('importRows').querySelectorAll('[data-track]:checked').length;});
    $('saveImport').onclick=()=>action(async()=>{const selected=[...$('importRows').querySelectorAll('[data-track]:checked')].map(c=>candidates[Number(c.value)]);if(!selected.length)throw Error('Zaznacz co najmniej jednego kontrahenta.');chooseCandidates(selected,batches,transactions);});
    notice('Odczytano kontrahentów. Wybierz pozycje do kontroli.');return;
  }
  const matched=P.tracked(transactions,state.rules),unknown=P.tracked(unread,state.rules);
  modal('Uzupełnij historię',`<p>Znaleziono ${matched.length} płatności dla kontrahentów z Twojej listy. Pozostałe operacje zostaną pominięte.</p>${unknown.length?`<p class="error">${unknown.length} płatności z listy ma nierozpoznaną kwotę i nie zostanie zapisanych.</p>`:''}${importOptions(batches)}`,`<button id="saveImport" class="primary">Zapisz historię wybranych pozycji</button>`);
  $('saveImport').onclick=()=>action(async()=>{const next=structuredClone(state),before=next.transactions.length;appendImport(next,batches,transactions);await persist(next);if(epoch!==generation)return;close();notice(`Dodano ${next.transactions.length-before} płatności do historii Twojej listy. Powtórzenia pominięto.`);});
}
function mergeChoice(candidate){const similar=P.similarRules(candidate,state.rules);return similar.length?`<p>Podobny odbiorca jest już na Twojej liście. Scalenie zachowa nazwę i ustawienia istniejącej pozycji oraz dopisze rozpoznawanie tego odbiorcy.</p><label>Co zrobić z tą pozycją?<select data-merge><option value="">Dodaj jako osobną pozycję</option>${similar.map(r=>`<option value="${escape(r.id)}">Scal z: ${escape(r.name)}</option>`).join('')}</select></label>`:'';}
function chooseCandidates(candidates,batches,transactions){
  modal('Ustaw wybrane pozycje',`<p>Ustaw nazwę i oczekiwaną kwotę. Listę możesz później zmienić w „Edytuj listę”.</p>${candidates.map((t,i)=>`<div class="rule" data-candidate="${i}"><b>${escape(t.recipient)}</b>${mergeChoice(t)}<div class="form-grid" data-new-fields><label>Nazwa pozycji<input data-name value="${escape(t.recipient)}"></label><label>Oczekiwana kwota (puste = zmienna)<input data-expected inputmode="decimal" value="${t.amount==null?'':(t.amount/100).toFixed(2)}"></label><label>Waluta<select data-currency>${(t.currencies.length?t.currencies:['PLN']).map(c=>`<option>${c}</option>`).join('')}</select></label><label>Kontroluj od<input data-start type="month" value="${t.date.slice(0,7)}"></label><label>Termin: dzień miesiąca<input data-day type="number" min="1" max="31" value="${Number(t.date.slice(8))}"></label><label>Przelew dotyczy<select data-offset><option value="0">Miesiąca przelewu</option><option value="-1">Poprzedniego miesiąca</option><option value="1">Następnego miesiąca</option></select></label><label>Fragment tytułu (opcjonalnie)<input data-phrase placeholder="np. alimenty"></label></div></div>`).join('')}${importOptions(batches)}`,`<button id="saveCandidates" class="primary">Zapisz listę i jej historię</button>`);
  $('modalBody').querySelectorAll('[data-merge]').forEach(select=>select.onchange=()=>{select.closest('[data-candidate]').querySelector('[data-new-fields]').hidden=!!select.value;});
  $('saveCandidates').onclick=()=>action(async()=>{const next=structuredClone(state);for(const block of $('modalBody').querySelectorAll('[data-candidate]')){const t=candidates[Number(block.dataset.candidate)],merge=block.querySelector('[data-merge]')?.value;if(merge){const target=next.rules.find(r=>r.id===merge);if(!target||target.currency!==t.currency)throw Error('Nieprawidłowa pozycja do scalenia.');P.linkContractor(target,t);continue;}const name=block.querySelector('[data-name]').value.trim(),v=block.querySelector('[data-expected]').value.trim(),expected=v?P.cents(v):null,start=block.querySelector('[data-start]').value,day=Number(block.querySelector('[data-day]').value),offset=Number(block.querySelector('[data-offset]').value),phrase=block.querySelector('[data-phrase]').value.trim(),currency=block.querySelector('[data-currency]').value;
    if(!name||v&&(expected==null||expected<0)||!start||!Number.isInteger(day)||day<1||day>31)throw Error('Popraw nazwę, kwotę, termin i miesiąc pozycji.');
    next.rules.push({id:id(),name,expected,currency,recipient:t.recipient,account:t.account,accounts:t.accounts,phrase,day,offset,start,end:null});
  }appendImport(next,batches,transactions);await persist(next);close();});
}
function download(data,name){const url=URL.createObjectURL(new Blob([JSON.stringify(data)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),15000);}
function settings(){modal('Ustawienia',`<h3>Zabezpieczenie</h3><p>Dane odszyfrowuje Twój PIN lub hasło. Nie ma możliwości odzyskania ich bez niego. Narzędzie blokuje się po 10 minutach bezczynności.</p><div class="form-grid"><label>Nowy PIN lub hasło<input id="newPin" type="password" autocomplete="new-password" minlength="6"></label><label>Powtórz<input id="confirmPin" type="password" autocomplete="new-password"></label></div><button id="changePin">Zmień PIN</button><hr><h3>Zaszyfrowana kopia</h3><p>Kopia zawiera listę i historię. Przywrócenie zastępuje obecne dane. Potrzebny jest PIN obowiązujący podczas utworzenia kopii.</p><div class="actions"><button id="exportBackup">Pobierz kopię</button><button id="restoreBackup">Przywróć kopię</button></div><hr><h3>Zaimportowane wyciągi</h3>${state.imports.map(i=>`<div class="rule"><b>${escape(i.name)}</b><p>${escape(i.from||'?')} – ${escape(i.to||'?')} · ${i.complete?'pełny okres':'niepotwierdzona kompletność'}</p><button data-range="${i.id}">Edytuj zakres</button></div>`).join('')||'<p>Brak wyciągów.</p>'}`);$('changePin').onclick=()=>action(async()=>{const pin=$('newPin').value;if(pin.length<6||pin!==$('confirmPin').value)throw Error('Nowy PIN musi mieć minimum 6 znaków; oba wpisy muszą być identyczne.');const nextSalt=newSalt(),nextKey=await keyFor(pin,nextSalt);await persist(structuredClone(state),nextKey,nextSalt);close();});$('exportBackup').onclick=()=>download(envelope,'Moje-platnosci-kopia-'+today()+'.json');$('restoreBackup').onclick=()=>{$('backupFile').click();};$('modalBody').querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{const item=state.imports.find(i=>i.id===b.dataset.range);modal('Zakres wyciągu',`<p>${escape(item.name)}</p><div class="form-grid"><label>Od<input id="rangeFrom" type="date" value="${item.from||''}"></label><label>Do<input id="rangeTo" type="date" value="${item.to||''}"></label></div><label class="checkline"><input id="rangeComplete" type="checkbox" ${item.complete?'checked':''}>Wyciąg obejmuje wszystkie operacje z tego okresu</label>`,`<button id="saveRange" class="primary">Zapisz zakres</button>`);$('saveRange').onclick=()=>action(async()=>{const from=$('rangeFrom').value,to=$('rangeTo').value,complete=$('rangeComplete').checked;if(!P.date(from)||!P.date(to)||from>to)throw Error('Podaj poprawny zakres.');if(complete&&item.unreadCount)throw Error('Ten wyciąg ma nierozpoznane operacje i nie może potwierdzać kompletności miesiąca.');if(complete&&state.transactions.some(t=>t.sourceHash===item.hash&&(t.date<from||t.date>to)))throw Error('Przelewy wykraczają poza ten zakres.');const next=structuredClone(state);Object.assign(next.imports.find(i=>i.id===item.id),{from,to,complete});await persist(next);close();});});}
$('backupFile').onchange=()=>action(async()=>{const file=$('backupFile').files[0];$('backupFile').value='';if(!file)return;if(file.size>25*1024*1024)throw Error('Kopia jest za duża.');const incoming=checkEnvelope(JSON.parse(await file.text()));modal('Przywróć kopię',`<p>Ta operacja zastąpi bieżącą listę i historię. Najpierw pobierz kopię bieżących danych w ustawieniach.</p><label>PIN lub hasło zapisane w kopii<input id="backupPin" type="password"></label>`,`<button id="confirmRestore" class="primary">Przywróć i zastąp dane</button>`);$('confirmRestore').onclick=()=>action(async()=>{const backupKey=await keyFor($('backupPin').value,incoming.salt);let restored;try{restored=validate(await open(incoming,backupKey));}catch(_){throw Error('Nieprawidłowy PIN kopii lub uszkodzona kopia.');}await persist(restored);close();});});
$('unlockForm').onsubmit=async e=>{e.preventDefault();const pin=$('pin').value;if(pin.length<6){$('gateError').textContent='Minimum 6 znaków.';return;}document.activeElement?.blur();$('unlock').disabled=true;$('gateError').textContent='';try{await loadEnvelope();const epoch=generation;let next,derived;const nextSalt=envelope?.salt||newSalt();if(!envelope&&pin!==$('repeatPin').value)throw Error('Powtórz ten sam PIN lub hasło.');derived=await keyFor(pin,nextSalt);if(envelope){try{next=validate(await open(envelope,derived));}catch(_){throw Error('Nieprawidłowy PIN lub hasło.');}}else next=empty();if(epoch!==generation)return;key=derived;salt=nextSalt;state=next;if(!envelope){await persist(next);} $('gate').hidden=true;$('main').hidden=false;$('pin').value='';$('repeatPin').value='';$('repeatLabel').hidden=true;$('repeatPin').required=false;$('unlock').textContent='Odblokuj';render();activity();requestAnimationFrame(()=>window.scrollTo({top:0,left:0,behavior:'auto'}));}catch(e){key=null;state=null;$('gateError').textContent=e.message;}finally{$('unlock').disabled=false;}};
$('editList').onclick=()=>editList();$('mergeList').onclick=showMergeList;$('import').onclick=()=>choosePdf();$('history').onclick=showHistory;$('settings').onclick=settings;$('lock').onclick=lock;$('year').onchange=render;$('closeModal').onclick=close;$('modal').addEventListener('cancel',e=>{if(busy)e.preventDefault();else passwordPromptCancel?.();});$('pdfFile').onchange=()=>{const files=[...$('pdfFile').files];$('pdfFile').value='';handlePdfFiles(files);};
for(const event of ['pointerdown','keydown','scroll'])document.addEventListener(event,activity,{passive:true});window.addEventListener('pagehide',lock);document.addEventListener('visibilitychange',()=>{if(document.hidden){clearTimeout(lockTimer);lockTimer=setTimeout(lock,60000);}else activity();});
async function init(){try{if(!window.supabase)throw Error('Nie udało się załadować logowania. Odśwież stronę.');db=window.supabase.createClient('https://nxmrobbhfqijmbjjzbof.supabase.co','sb_publishable_9lz7NUv2-MloX7MEcH2-vQ_AZS8IIHz');const {data,error}=await db.auth.getUser();if(error||!data?.user)throw Error('Zaloguj się w panelu CleanFleet jako administrator, a następnie otwórz narzędzie ponownie.');user=data.user;const role=await db.rpc('cf_is_admin');if(role.error||role.data!==true)throw Error('To narzędzie jest dostępne tylko dla administratora.');await loadEnvelope();$('gateInfo').textContent=envelope?'Wpisz PIN lub hasło, aby odszyfrować płatności.':'Ustaw własny PIN (minimum 6 znaków) lub dłuższe hasło. Zapamiętaj je — bez niego nie odzyskasz danych.';$('repeatLabel').hidden=!!envelope;$('repeatPin').required=!envelope;$('unlock').textContent=envelope?'Odblokuj':'Ustaw PIN i otwórz';$('unlockForm').hidden=false;db.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'||session&&session.user.id!==user.id){lock();$('unlockForm').hidden=true;$('gateError').textContent='Sesja administratora została zakończona.';}});}catch(e){$('gateInfo').textContent=e.message;$('unlockForm').hidden=true;}}
init();
